### ISSUE TITLE
SWAP BTC/DAI went good but CLI failed

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#1063]
```
xud@xud-test-3:~/scripts/raiden$ xucli sell 0.001 BTC/DAI 11000
Error: 13 INTERNAL: Assertion failed
xud@xud-test-3:~/scripts/raiden$ 
```

Log files on test1 and test3 shows swap success
```
24/06/2019 21:51:47.200 [RPC] debug: received call /xudrpc.Xud/PlaceOrderSync
24/06/2019 21:51:47.202 [ORDERBOOK] debug: reduced order 43d5d910-96c6-11e9-a81c-cfff346a5cdd by 100000 quantity while matching order 43874710-96ca-11e9-ae4c-3fc0f3e079c4
24/06/2019 21:51:47.203 [ORDERBOOK] debug: matched with peer 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6, executing swap on taker 43874710-96ca-11e9-ae4c-3fc0f3e079c4 and maker 43d5d910-96c6-11e9-a81c-cfff346a5cdd for 100000
24/06/2019 21:51:47.211 [LND-BTC] debug: got 1 route(s) to destination 03a0bdf210dcecebb2d6f092b47fb7753af8114261888a365dfcb0d4548bbbdd2a: 1903,,100000,1671257674285057,2500000000,100000,,1903,100000000,,03a0bdf210dcecebb2d6f092b47fb7753af8114261888a365dfcb0d4548bbbdd2a,,100000000, finalCltvDelta: 144
24/06/2019 21:51:47.212 [SWAPS] debug: New deal: {"takerCltvDelta":1,"rHash":"de1202a046674896645127aa44684a0c1328421b65220836ec6f7032fbd9fa0c","orderId":"43d5d910-96c6-11e9-a81c-cfff346a5cdd","pairId":"BTC/DAI","proposedQuantity":100000,"rPreimage":"3b89f60d6f08d8a90409345fd41d980e5b2cdc003bd57064bfed48ed4a7915aa","takerCurrency":"DAI","makerCurrency":"BTC","takerAmount":11000000000000000000,"makerAmount":100000,"destination":"03a0bdf210dcecebb2d6f092b47fb7753af8114261888a365dfcb0d4548bbbdd2a","peerPubKey":"02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6","localId":"43874710-96ca-11e9-ae4c-3fc0f3e079c4","price":11000,"isBuy":true,"phase":0,"state":0,"role":0,"createTime":1561413107212}
24/06/2019 21:51:47.214 [SWAPS] debug: Requesting deal: {"takerCltvDelta":1,"rHash":"de1202a046674896645127aa44684a0c1328421b65220836ec6f7032fbd9fa0c","orderId":"43d5d910-96c6-11e9-a81c-cfff346a5cdd","pairId":"BTC/DAI","proposedQuantity":100000,"rPreimage":"3b89f60d6f08d8a90409345fd41d980e5b2cdc003bd57064bfed48ed4a7915aa","takerCurrency":"DAI","makerCurrency":"BTC","takerAmount":11000000000000000000,"makerAmount":100000,"destination":"03a0bdf210dcecebb2d6f092b47fb7753af8114261888a365dfcb0d4548bbbdd2a","peerPubKey":"02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6","localId":"43874710-96ca-11e9-ae4c-3fc0f3e079c4","price":11000,"isBuy":true,"phase":0,"state":0,"role":0,"createTime":1561413107212}
24/06/2019 21:51:47.246 [P2P] debug: received swapAccepted from 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6: {"rHash":"de1202a046674896645127aa44684a0c1328421b65220836ec6f7032fbd9fa0c","quantity":100000,"makerCltvDelta":144}
24/06/2019 21:51:47.249 [LND-BTC] debug: executing sendPaymentSync -
          destination: 03a0bdf210dcecebb2d6f092b47fb7753af8114261888a365dfcb0d4548bbbdd2a, rHash: de1202a046674896645127aa44684a0c1328421b65220836ec6f7032fbd9fa0c, amount: 100000, FinalCltvDelta: 144
24/06/2019 21:51:47.823 [HTTP] debug: http server request json: {"token":"0x76671a2831dc0af53b09537dea57f1e22899655d","secrethash":"0xde1202a046674896645127aa44684a0c1328421b65220836ec6f7032fbd9fa0c","amount":11000000000000000000,"payment_identifier":4079280201333692,"payment_sender":"0x7ed0299fa1ada71d10536b866231d447cdfa48b9","expiration":2131427,"payment_recipient":"0x283ead0338f8c202b996146d77a542fdfb60d437","reveal_timeout":50,"settle_timeout":500}
24/06/2019 21:51:47.824 [SWAPS] debug: handleResolveRequest starting with hash de1202a046674896645127aa44684a0c1328421b65220836ec6f7032fbd9fa0c
24/06/2019 21:51:47.828 [SWAPS] debug: Executing taker code to resolve hash
24/06/2019 21:51:47.829 [SWAPS] debug: Amount received for deal with payment hash 3b89f60d6f08d8a90409345fd41d980e5b2cdc003bd57064bfed48ed4a7915aa
24/06/2019 21:51:47.888 [ORDERBOOK] info: match executed on taker 43874710-96ca-11e9-ae4c-3fc0f3e079c4 and maker 43d5d910-96c6-11e9-a81c-cfff346a5cdd for 100000 with peer 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6
24/06/2019 21:51:48.749 [SWAPS] debug: Swap completed. preimage = 3b89f60d6f08d8a90409345fd41d980e5b2cdc003bd57064bfed48ed4a7915aa
24/06/2019 21:51:48.750 [SWAPS] debug: Sending swap complete to peer: {"rHash":"de1202a046674896645127aa44684a0c1328421b65220836ec6f7032fbd9fa0c"}
```

**Comment by offerm** [comment]
If this helps:

```
xud@xud-test-3:~/scripts/raiden$ xucli sell 0.001 BTC/DAI 11000.0 --stream
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: 13 INTERNAL: Assertion failed
    at Object.exports.createStatusError (/opt/xud/node_modules/grpc/src/common.js:91:15)
    at ClientReadableStream._emitStatusIfDone (/opt/xud/node_modules/grpc/src/client.js:233:26)
    at ClientReadableStream._receiveStatus (/opt/xud/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/opt/xud/node_modules/grpc/src/client_interceptors.js:1272:15)
    at InterceptingListener._callNext (/opt/xud/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/opt/xud/node_modules/grpc/src/client_interceptors.js:618:8)
    at /opt/xud/node_modules/grpc/src/client_interceptors.js:1029:24
Emitted 'error' event at:
    at ClientReadableStream._emitStatusIfDone (/opt/xud/node_modules/grpc/src/client.js:234:12)
    at ClientReadableStream._receiveStatus (/opt/xud/node_modules/grpc/src/client.js:211:8)
    [... lines matching original stack trace ...]
    at /opt/xud/node_modules/grpc/src/client_interceptors.js:1029:24
```

**Comment by sangaman** [comment]
I think the what's happening here is that 11000 DAI denominated in wei is exceeding the int64 limit we're using for the protobuf definition for `amount_received` and `amount_sent`.

Probably the best solution would be to scale these back to satoshi units rather than wei, that way we won't be pushing up against the limits of 64 bit integers.

**Comment by kilrau** [comment]
@sangaman pls give it a manual test

**Comment by kilrau** [comment]
Satus: good to be merged
