### ISSUE TITLE
xud crashes when connecting to peer timeouts

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#1129]
```
xud_1     | 07/08/2019 08:30:17.442 [P2P] info: Connecting to known / previously connected peers
xud_1     | 07/08/2019 08:30:32.466 [P2P] error: Peer (127.0.0.1:34058): error: response timeout (SessionInit)
xud_1     | 07/08/2019 08:30:32.469 [P2P] debug: Peer (127.0.0.1:34058): closing socket. reason: ResponseStalling
xud_1     | 07/08/2019 08:30:32.478 [P2P] warn: could not open connection to peer (127.0.0.1:34058): response timeout (SessionInit)
xud_1     | Error: response timeout (95f82ba0-b8ed-11e9-a682-c9e653865293)
xud_1     |     at Peer.emitError (/app/dist/p2p/Peer.js:534:36)
xud_1     |     at Peer.<anonymous> (/app/dist/p2p/Peer.js:382:26)
xud_1     |     at Generator.next (<anonymous>)
xud_1     |     at /app/dist/p2p/Peer.js:7:71
xud_1     |     at new Promise (<anonymous>)
xud_1     |     at __awaiter (/app/dist/p2p/Peer.js:3:12)
xud_1     |     at Timeout.Peer.checkTimeout [as _onTimeout] (/app/dist/p2p/Peer.js:376:35)
xud_1     |     at ontimeout (timers.js:436:11)
xud_1     |     at tryOnTimeout (timers.js:300:5)
xud_1     |     at listOnTimeout (timers.js:263:5)
xud_1     |     at Timer.processTimers (timers.js:223:10)
```

**Comment by erkarl** [comment]
Looks like this can only reproduced when attempting the initial connection to peer (not reconnecting).

**Comment by erkarl** [comment]
I experienced a crash with similar stack trace on latest master `365b52bd3001b1ab229b7bdcb33791c53645ecca`:

```
xud_1     | 19/09/2019 12:22:46.443 [P2P] warn: could not open connection to peer (127.0.0.1:50958): response timeout (SessionInit)
xud_1     | Error: response timeout (SessionAck)
xud_1     |     at Peer.emitError (/app/dist/p2p/Peer.js:534:36)
xud_1     |     at Peer.<anonymous> (/app/dist/p2p/Peer.js:382:26)
xud_1     |     at Generator.next (<anonymous>)
xud_1     |     at /app/dist/p2p/Peer.js:7:71
xud_1     |     at new Promise (<anonymous>)
xud_1     |     at __awaiter (/app/dist/p2p/Peer.js:3:12)
xud_1     |     at Timeout.Peer.checkTimeout [as _onTimeout] (/app/dist/p2p/Peer.js:376:35)
xud_1     |     at ontimeout (timers.js:436:11)
xud_1     |     at tryOnTimeout (timers.js:300:5)
xud_1     |     at listOnTimeout (timers.js:263:5)
xud_1     |     at Timer.processTimers (timers.js:223:10)
xud_1     | 2019-09-19 12:22:46,456 INFO exited: xud (exit status 1; not expected)
```

**Comment by kilrau** [comment]
Experienced this today too:
```
xud_1     | 05/10/2019 10:00:17.760 [P2P] info: Peer 02b59b2c611c161b6a43bcf314c3678c50e288a33f2650c3b5fe99dbead96ec74a socket closed
xud_1     | 05/10/2019 10:00:17.762 [P2P] warn: could not open connection to peer (02c17d378b153068830c5c203490c8c1d0dc2557d7708df46e50bc4ba32a17cc6e@glqlnsfhhsrx7sumd4aif4eukvl73bn4ghgmqr7oza737etejssvcdad.onion:28885): could not connect to peer at glqlnsfhhsrx7sumd4aif4eukvl73bn4ghgmqr7oza737etejssvcdad.onion:28885: connect ECONNREFUSED 224.0.0.5:28885
xud_1     | Oct 05 10:00:27.000 [notice] Closed 1 streams for service [scrubbed].onion for reason resolve failed. Fetch status: No more HSDir available to query.
xud_1     | Error: response timeout (eaa47180-e756-11e9-b04d-b943bc180572) 
xud_1     |     at Peer.emitError (/app/dist/p2p/Peer.js:534:36)
xud_1     |     at Peer.<anonymous> (/app/dist/p2p/Peer.js:382:26)
xud_1     |     at Generator.next (<anonymous>)
xud_1     |     at /app/dist/p2p/Peer.js:7:71
xud_1     |     at new Promise (<anonymous>)
xud_1     |     at __awaiter (/app/dist/p2p/Peer.js:3:12)
xud_1     |     at Timeout.Peer.checkTimeout [as _onTimeout] (/app/dist/p2p/Peer.js:376:35)
xud_1     |     at ontimeout (timers.js:436:11)
xud_1     |     at tryOnTimeout (timers.js:300:5)
xud_1     |     at listOnTimeout (timers.js:263:5)
xud_1     |     at Timer.processTimers (timers.js:223:10)
xud_1     | 2019-10-05 10:00:27,240 INFO exited: xud (exit status 1; not expected)
xud_1     | 2019-10-05 10:00:28,242 INFO spawned: 'xud' with pid 223
xud_1     | Detecting localnet IP for lndbtc...
xud_1     | Detecting localnet IP for lndltc...
xud_1     | Detecting localnet IP for raiden...
xud_1     | 05/10/2019 10:00:29.114 [GLOBAL] info: config file loaded
xud_1     | 05/10/2019 10:00:29.225 [DB] info: connected to database /root/.xud/xud-simnet.db
```

supervisord kept restarting xud

**Comment by erkarl** [comment]
Upping the priority to P1 since it seems to cause crash loops.
