### ISSUE TITLE
xud crashes after a failed swap

### ISSUE THREAD

**Issue by erkarl** [ExchangeUnion/xud#1155]
Steps to reproduce:
1. Provision a clean `xud-simnet` machine
2. Make sure `lnd-ltc` has a channel to test2 (and not test1)
3. `xucli buy 0.1 ltc/btc 0.0079`

Logs:
```
16/08/2019 11:03:47.749 [ORDERBOOK] debug: matched with peer 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6, executing swap on taker 8575d910-c015-11e9-a749-7940ba28b9a6 and maker cdc365f0-c012-11e9-ba33-1dd8acf2144f for 10000000
16/08/2019 11:03:47.784 [LND-BTC] debug: got 1 route(s) to destination 03a0bdf210dcecebb2d6f092b47fb7753af8114261888a365dfcb0d4548bbbdd2a: 62066,1,79001,67988301503594497,2500000000,79000,1,62026,79000000,1079,023f4a4fa9166f1beb2616bf0cce2c5a4fc9fcda6d533cb760bb6630487bfafdf9,17109500441001985,2500000000,79000,,62026,79000000,,03a0bdf210dcecebb2d6f092b47fb7753af8114261888a365dfcb0d4548bbbdd2a,1079,79001079, finalCltvDelta: 144
16/08/2019 11:03:47.787 [SWAPS] debug: New deal: {"takerCltvDelta":160,"rHash":"4818de6f4d0c4f2488e799a5704d9723f883a864a530c7930c77dee2f9f027ea","orderId":"cdc365f0-c012-11e9-ba33-1dd8acf2144f","pairId":"LTC/BTC","proposedQuantity":10000000,"rPreimage":"eb8c722259f3fc4589552a6a15557c0e74cc6c3bddca38ed435d4b2685c9becc","takerCurrency":"LTC","makerCurrency":"BTC","takerAmount":10000000,"makerAmount":79000,"takerUnits":10000000,"makerUnits":79000,"destination":"03a0bdf210dcecebb2d6f092b47fb7753af8114261888a365dfcb0d4548bbbdd2a","peerPubKey":"02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6","localId":"8575d910-c015-11e9-a749-7940ba28b9a6","price":0.0079,"isBuy":false,"phase":0,"state":0,"role":0,"createTime":1565953427787}
16/08/2019 11:03:47.791 [SWAPS] debug: Requesting deal: {"takerCltvDelta":160,"rHash":"4818de6f4d0c4f2488e799a5704d9723f883a864a530c7930c77dee2f9f027ea","orderId":"cdc365f0-c012-11e9-ba33-1dd8acf2144f","pairId":"LTC/BTC","proposedQuantity":10000000,"rPreimage":"eb8c722259f3fc4589552a6a15557c0e74cc6c3bddca38ed435d4b2685c9becc","takerCurrency":"LTC","makerCurrency":"BTC","takerAmount":10000000,"makerAmount":79000,"takerUnits":10000000,"makerUnits":79000,"destination":"03a0bdf210dcecebb2d6f092b47fb7753af8114261888a365dfcb0d4548bbbdd2a","peerPubKey":"02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6","localId":"8575d910-c015-11e9-a749-7940ba28b9a6","price":0.0079,"isBuy":false,"phase":0,"state":0,"role":0,"createTime":1565953427787}
16/08/2019 11:03:48.009 [P2P] debug: received swapAccepted from 02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6: {"rHash":"4818de6f4d0c4f2488e799a5704d9723f883a864a530c7930c77dee2f9f027ea","quantity":10000000,"makerCltvDelta":328}
16/08/2019 11:03:48.019 [LND-LTC] debug: added invoice of 10000000 for 4818de6f4d0c4f2488e799a5704d9723f883a864a530c7930c77dee2f9f027ea with cltvExpiry 160
16/08/2019 11:03:48.950 [SWAPS] debug: deal 4818de6f4d0c4f2488e799a5704d9723f883a864a530c7930c77dee2f9f027ea failed due to SendPaymentFailure
16/08/2019 11:03:48.955 [SWAPS] debug: Sending swap error to peer: {"rHash":"4818de6f4d0c4f2488e799a5704d9723f883a864a530c7930c77dee2f9f027ea","failureReason":7,"errorMessage":"UnknownPaymentHash(amt=79000000 mSAT)"}
16/08/2019 11:03:48.956 [ORDERBOOK] error: swap between orders cdc365f0-c012-11e9-ba33-1dd8acf2144f & 8575d910-c015-11e9-a749-7940ba28b9a6 failed due to SendPaymentFailure
16/08/2019 11:03:48.957 [ORDERBOOK] warn: swap for 10000000 failed during order matching due to SendPaymentFailure, will repeat matching routine for failed quantity
16/08/2019 11:03:48.957 [ORDERBOOK] debug: repeating matching routine for 8575d910-c015-11e9-a749-7940ba28b9a6 for failed quantity of 10000000
16/08/2019 11:03:48.958 [ORDERBOOK] debug: order added: {"pairId":"LTC/BTC","price":0.0079,"quantity":10000000,"isBuy":true,"localId":"8575d910-c015-11e9-a749-7940ba28b9a6","hold":0,"id":"8575d910-c015-11e9-a749-7940ba28b9a6","initialQuantity":10000000,"createdAt":1565953427745}
{ AssertionError [ERR_ASSERTION]: deal is not Active. Can not change deal phase
    at Swaps.<anonymous> (/home/ar/xud-simnet/xud/dist/swaps/Swaps.js:729:29)
    at Generator.next (<anonymous>)
    at /home/ar/xud-simnet/xud/dist/swaps/Swaps.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ar/xud-simnet/xud/dist/swaps/Swaps.js:3:12)
    at Swaps.setDealPhase (/home/ar/xud-simnet/xud/dist/swaps/Swaps.js:728:49)
    at Swaps.<anonymous> (/home/ar/xud-simnet/xud/dist/swaps/Swaps.js:500:24)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ar/xud-simnet/xud/dist/swaps/Swaps.js:4:58)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
```

**Comment by offerm** [comment]
Also, can we have these assets going to the log?

**Comment by sangaman** [comment]
I'm looking into it.

> Also, can we have these assets going to the log?

Which assets?

**Comment by offerm** [comment]
> I'm looking into it.
> 
> > Also, can we have these assets going to the log?
> 
> Which assets?

Sorry, typo.

can we have these asserts going to the log?
