### ISSUE TITLE
npm i failed on rasbberry pi 3

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#1198]
installing xud from source on pi3
ARM v71 processor

```
xud@lightning:~/xud $ npm i

> grpc-tools@1.6.0 install /home/xud/xud/node_modules/grpc-tools
> node-pre-gyp install

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc-tools/v1.6.0/linux-arm.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/home/xud/xud/node_modules/grpc-tools/node_modules/node-pre-gyp/lib/install.js:118:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:203:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/home/xud/xud/node_modules/request/request.js:1066:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:198:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:442:20)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:198:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:288:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:269:11)
node-pre-gyp ERR! System Linux 4.19.58-v7+
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/xud/xud/node_modules/grpc-tools/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /home/xud/xud/node_modules/grpc-tools
node-pre-gyp ERR! node -v v10.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.37
node-pre-gyp ERR! not ok 
403 status code downloading tarball https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc-tools/v1.6.0/linux-arm.tar.gz
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc-tools@1.6.0 install: `node-pre-gyp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc-tools@1.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xud/.npm/_logs/2019-09-03T12_55_00_426Z-debug.log
xud@lightning:~/xud $ 
```

**Comment by offerm** [comment]
solved by using `npm install --production`
