### ISSUE TITLE
staring xud on pi 3 for the first time

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#1199]
Got this nice message:

```
(node:15167) ExperimentalWarning: The fs.promises API is experimental
03/09/2019 10:13:19.560 [GLOBAL] info: config loaded
03/09/2019 10:13:20.121 [GLOBAL] error: Unexpected error during initialization, shutting down...: Error: Please install sqlite3 package manually
    at new ConnectionManager (/home/xud/xud/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:31:15)
    at new SqliteDialect (/home/xud/xud/node_modules/sequelize/lib/dialects/sqlite/index.js:14:30)
    at new Sequelize (/home/xud/xud/node_modules/sequelize/lib/sequelize.js:242:20)
    at new DB (/home/xud/xud/dist/db/DB.js:120:26)
    at Xud.<anonymous> (/home/xud/xud/dist/Xud.js:52:27)
    at Generator.next (<anonymous>)
    at fulfilled (/home/xud/xud/dist/Xud.js:4:58)
03/09/2019 10:13:20.124 [GLOBAL] info: XUD is shutting down
TypeError: Cannot read property 'close' of undefined
    at Xud.<anonymous> (/home/xud/xud/dist/Xud.js:175:27)
    at Generator.next (<anonymous>)
    at fulfilled (/home/xud/xud/dist/Xud.js:4:58)
/home/xud/xud/dist/bootstrap.js:13
        throw err;
        ^

TypeError: Cannot read property 'close' of undefined
    at Xud.<anonymous> (/home/xud/xud/dist/Xud.js:175:27)
    at Generator.next (<anonymous>)
    at fulfilled (/home/xud/xud/dist/Xud.js:4:58)
```

```
xud@lightning:~/scripts $ uname -a
Linux lightning 4.19.58-v7+ #1245 SMP Fri Jul 12 17:25:51 BST 2019 armv7l GNU/Linux
```

```
xud@lightning:~/scripts $ npm --version
6.9.0
xud@lightning:~/scripts $ node --version
v10.16.3
```

**Comment by offerm** [comment]
Managed to solve this problem by:

1. remove sqlite form package.json
2. build from source with `npm install sqlite3 --build-from-source --sqlite=/usr --save
`

**Comment by michael1011** [comment]
@kilrau should we document this somewhere in case someone has a similar problem in the future?

**Comment by kilrau** [comment]
Done: https://github.com/ExchangeUnion/docs/pull/52

**Comment by sangaman** [comment]
Looks like others have had this same issue in other apps that use `sequelize`: https://github.com/sequelize/sequelize/issues/11174

@offerm  How did you install xud on the pi? Is this via docker?

**Comment by offerm** [comment]
No. Directly on the pi

**Comment by sangaman** [comment]
OK, you cloned the repo from github and ran `npm install` then?

**Comment by offerm** [comment]
yep
