### ISSUE TITLE
Cannot find module 'compute-gammainc'

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1255]
### Background

xud doesn't start because of a missing module

### Your environment

* version of `xud`: master
* which operating system (`uname -a` on *Nix): ubuntu 18.04.3
* version of `btcd`, `bitcoind`, `ltcd`, `litecoind`, `geth`, `parity`, `raiden`, `lnd` or other chain backend:
* any other relevant environment details:

### Steps to reproduce

`./xud`

### Expected behaviour

xud starts

### Actual behaviour

xud fails to start with

```
kilrau@K-Yoga:~/xud-simnet/xud/bin$ ./xud
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'compute-gammainc'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/kilrau/xud-simnet/xud/node_modules/distributions-poisson-cdf/lib/number.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/kilrau/xud-simnet/xud/node_modules/distributions-poisson-quantile/lib/number.js:5:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/kilrau/xud-simnet/xud/node_modules/distributions-poisson-quantile/lib/index.js:16:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

It looks like `compute-gammainc` was introduced with https://github.com/ExchangeUnion/xud/pull/1179/files#diff-36018a6a9e1de1798516799b84841318R2721

**Comment by kilrau** [comment]
Manually running `npm prune --dev` solved the issue. `xud` should run this automatically.

**Comment by kilrau** [comment]
https://paste.ubuntu.com/p/M5hvPnWhJv/

**Comment by sangaman** [comment]
This is a bug with newer versions of npm. Running `npm install` with npm 6.4.1 or 6.9.0 does not encounter this issue. Running with npm 6.11.3 does encounter this issue.
