### ISSUE TITLE
Intermittent failed Pool test

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/xud#1309]
There's a test case that fails intermittently in the Pool jest test suite, giving the following error:

```
FAIL  test/jest/Pool.spec.ts
 ● Console

   console.log node_modules/winston/lib/winston/transports/console.js:79
     2019-10-31 11:23:38.3838 [P2P] warn: could not open connection to peer (127.0.0.1:59962): could not authenticate peer (027ba09e90b1085bc651d40ac98b18be27b2e3188d3beea2ff203ed24e014c9a79): invalid target (0388d4d4a1bb551c247bf1ea87fe19da84c5e1e03df3d315250fe43a7397a7aa06)
     
   console.log node_modules/winston/lib/winston/transports/console.js:79
     2019-10-31 11:23:38.3838 [P2P] warn: could not open connection to peer (02ef10d41a52343e4406181e21272cda5eb7ff3793c1e6ee5b15c41ba346f26632): Peer 02ef10d41a52343e4406181e21272cda5eb7ff3793c1e6ee5b15c41ba346f26632 was destroyed
     
   console.log node_modules/winston/lib/winston/transports/console.js:79
     2019-10-31 11:23:38.3838 [P2P] warn: could not open connection to peer (033fc92de8d75951076786720887570f1dee12cf32c4c8fb336bbdb360b3cbb15f): node 033fc92de8d75951076786720887570f1dee12cf32c4c8fb336bbdb360b3cbb15f at 127.0.0.1:57918 already connected
     
   console.log node_modules/winston/lib/winston/transports/console.js:79
     2019-10-31 11:23:38.3838 [P2P] warn: could not open connection to peer (02e249349b309ce6b2aea65a965d806c7ce54b04e59d5d5a74c481e1379cf48fad@localhost:33953): Peer 02e249349b309ce6b2aea65a965d806c7ce54b04e59d5d5a74c481e1379cf48fad@localhost:33953 disconnected from us due to AlreadyConnected
     

 ● P2P Pool › it rejects when already connected

   expect(received).toEqual(expected) // deep equality

   Expected: 1
   Received: 0

     184 |       );
     185 |     }
   > 186 |     expect(pool['peers'].size).toEqual(1);
         |                                ^
     187 |     expect(pool2['peers'].size).toEqual(1);
     188 |   });
     189 | 

     at Pool.spec.ts:186:32
         at Generator.throw (<anonymous>)
     at rejected (Pool.spec.ts:6:65)
```

**Comment by kilrau** [comment]
How often does this occur? If edge case, I'd say P3 and not part of `1.0.0-beta`.

**Comment by sangaman** [comment]
> How often does this occur? If edge case, I'd say P3 and not part of `1.0.0-beta`.

It's somewhat common, if you try running `npm run test:jest` on current master you'll see it probably after a few tries. But I think this isn't just a false alarm, but actually alerting us to an actual flaw in the p2p pool logic. I believe that's all fixed in my PR though.
