### ISSUE TITLE
npm install not working on mac

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#1314]
When installing xud-simnet I have a problem with npm install:

```
npm install
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/ms-4a834ceb/package.json'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/debug-79277615/package.json'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/ms-4a834ceb/index.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/debug-79277615/CHANGELOG.md'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/ms-4a834ceb/license.md'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/debug-79277615/LICENSE'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/ms-4a834ceb/readme.md'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/@babel/helper-plugin-utils-9ebad5dd/LICENSE'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/debug-79277615/README.md'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/@babel/helper-plugin-utils-9ebad5dd/README.md'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/@babel/plugin-syntax-object-rest-spread-d21e689e/LICENSE'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/@babel/plugin-syntax-object-rest-spread-d21e689e/README.md'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/@types/bluebird-bd73de5e/package.json'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/@types/chai-2ee1cd95/package.json'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/@babel/parser-b0dc0720/package.json'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/@babel/parser-b0dc0720/CHANGELOG.md'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/@types/node-9fc1e474/module.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/@types/node-9fc1e474/net.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/@types/node-9fc1e474/os.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/@types/node-9fc1e474/package.json'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/@types/node-9fc1e474/path.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/@types/node-9fc1e474/perf_hooks.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/@types/node-9fc1e474/process.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/@types/node-9fc1e474/punycode.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/@types/node-9fc1e474/querystring.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/@types/node-9fc1e474/readline.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/@types/node-9fc1e474/repl.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/@types/node-9fc1e474/stream.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/@types/node-9fc1e474/string_decoder.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/@types/node-9fc1e474/timers.d.ts'
npm WARN tar ENOENT: no such file or directory, open '/Users/admin/xud-simnet/xud/node_modules/.staging/@types/node-9fc1e474/tls.d.ts'
npm ERR! Cannot read property 'resolve' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2019-11-01T09_54_50_112Z-debug.log
admins-MacBook-Pro-2:xud admin$ 
```
from log file:
```
7159 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.2 (node_modules/chokidar/node_modules/fsevents):
7160 warn optional SKIPPING OPTIONAL DEPENDENCY: Cannot read property 'resolve' of undefined
7161 warn @exchangeunion/grpc-dynamic-gateway@0.3.9 requires a peer of @types/express@4.16.0 but none is installed. You must install peer dependencies yourself.
7162 warn @exchangeunion/grpc-dynamic-gateway@0.3.9 requires a peer of express@4.16.3 but none is installed. You must install peer dependencies yourself.
7163 warn @exchangeunion/grpc-dynamic-gateway@0.3.9 requires a peer of grpc@1.21.1 but none is installed. You must install peer dependencies yourself.
7164 verbose stack TypeError: Cannot read property 'resolve' of undefined
7164 verbose stack     at regFetch (/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/index.js:76:23)
7164 verbose stack     at fromManifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/tarball.js:55:3)
7164 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/tarball.js:38:25
7164 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
7164 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
7164 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
7164 verbose stack     at Promise._settlePromiseCtx (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:611:10)
7164 verbose stack     at _drainQueueStep (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:142:12)
7164 verbose stack     at _drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
7164 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
7164 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
7164 verbose stack     at processImmediate (internal/timers.js:439:21)
7165 verbose cwd /Users/admin/xud-simnet/xud
7166 verbose Darwin 18.0.0
7167 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
7168 verbose node v12.13.0
7169 verbose npm  v6.12.0
7170 error Cannot read property 'resolve' of undefined
7171 verbose exit [ 1, true ]

```

npm install --prodution does not face that problem.

**Comment by sangaman** [comment]
Do you have any idea when this build issue started? When's the last time you successfully installed on mac?

**Comment by offerm** [comment]
nop.

I managed to fixed it with this

https://github.com/nodejs/help/issues/1941
(new npm).

For some reason I can't build xud with --production. you may want to check this.

**Comment by offerm** [comment]
npm install still fails with node 13.

**Comment by kilrau** [comment]
Thanks for opening this issue! I'd suggest the following: since we can't support `latest` nodejs/npm anyways because of a broken gRPC (https://github.com/ExchangeUnion/xud/pull/1312) let's focus on getting LTS to work and maintain it. Please revert to LTS @offerm 

Any other idea what it could be? @sangaman 

Could you also test on your Macs with latest nodejs/npm LTS? @reliveyy @dopetard

**Comment by sangaman** [comment]
FYI, node 13 should now work after #1316.

You can install on mac now but only without the `--production` flag, correct? I'm not getting an error running `npm install --production` on my machine with ubuntu. I can do some more testing on other machines but I don't have access to a mac currently.

**Comment by ymacora** [comment]
an option that work for me on catalina curl "https://nodejs.org/dist/v12.13.0/node-v12.13.0.pkg" > "$HOME/Downloads/node-latest.pkg" && sudo installer -store -pkg "$HOME/Downloads/node-latest.pkg" -target "/"

**Comment by kilrau** [comment]
Thanks @ymacora and... welcome!

**Comment by kilrau** [comment]
Closing. Please reopen if still in issue on some versions of macOS.
