### ISSUE TITLE
LndClient - Cannot read property 'getInfo' of undefined

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1367]
When running all internal, lnd's show `Cannot read property 'getInfo' of undefined` in `xucli getinfo`, even though they are unlocked and functional. Letting the whole environment run for 1h+, brings lnd's back to normal in `xucli getinfo`.

**Comment by erkarl** [comment]
Moving this under xud repository.

**Comment by kilrau** [comment]
```
16/01/2020 07:34:19.113 [LND-LTC] error: getinfo error: TypeError: Cannot read property 'getInfo' of undefined
    at /app/dist/lndclient/LndClient.js:171:31
    at new Promise (<anonymous>)
    at LndClient.unaryCall (/app/dist/lndclient/LndClient.js:166:20)
    at LndClient.getInfo (/app/dist/lndclient/LndClient.js:416:25)
    at LndClient.<anonymous> (/app/dist/lndclient/LndClient.js:245:56)
    at Generator.next (<anonymous>)
    at /app/dist/lndclient/LndClient.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/dist/lndclient/LndClient.js:4:12)
    at LndClient.getLndInfo (/app/dist/lndclient/LndClient.js:229:33)
    at SwapClientManager.<anonymous> (/app/dist/swaps/SwapClientManager.js:308:53)
    at Generator.next (<anonymous>)
    at /app/dist/swaps/SwapClientManager.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/dist/swaps/SwapClientManager.js:4:12)
    at SwapClientManager.getLndClientsInfo (/app/dist/swaps/SwapClientManager.js:299:40)
    at Service.<anonymous> (/app/dist/service/Service.js:270:54)
    at Generator.next (<anonymous>)
    at /app/dist/service/Service.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/dist/service/Service.js:4:12)
    at Service.getInfo (/app/dist/service/Service.js:251:30)
```

**Comment by erkarl** [comment]
Did some digging on this one:

- only happened with `lnd-ltc`
- lnd was waiting for litecoind to finish syncing
- xud didn't update its status when lnd became synced
