### ISSUE TITLE
Connext client blocks getbalance request when container is down or connext node returns error

### ISSUE THREAD

**Issue by raladev** [ExchangeUnion/xud#1572]
[Screenshot from 2020-05-22 14-51-05](https://user-images.githubusercontent.com/29906866/82665286-24f18400-9c3c-11ea-92a6-69ac8f08a98b.png)
[Screenshot from 2020-05-22 14-50-50](https://user-images.githubusercontent.com/29906866/82665292-258a1a80-9c3c-11ea-8ad0-937a386698f5.png)

### Actual behaviour

1. getbalance command returns connext error if connext got 500 error
2. getbalance command returns 'UNKNOWN: getaddrinfo ENOTFOUND connext' if connext container was stopped

### Expected behaviour

1. getbalance command returns all balances except of connext balance
2. getbalance command returns all balances except of connext balance

**Comment by kilrau** [comment]
Just had this too:
```
simnet > getbalance
Error: 2 UNKNOWN: connext server error
```

```
2020-06-02T08:51:13.866Z [CF-RpcRouter] Processed chan_getFreeBalanceState method in 49 ms
2020-06-02T08:51:13.872Z [CF-RpcRouter] Processed chan_getFreeBalanceState method in 51 ms
[1591087873945] ERROR (71 on connext): contract not deployed (contractAddress="0x468ee988fD0228A79f6CcC33fEc04249cdfD809E", operation="getDeployed", version=4.0.46)
    Error: contract not deployed (contractAddress="0x468ee988fD0228A79f6CcC33fEc04249cdfD809E", operation="getDeployed", version=4.0.46)
        at Object.throwError (/app/node_modules/ethers/errors.js:76:17)
        at /app/node_modules/ethers/contract.js:353:32
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async Promise.all (index 0)
[1591087873952] ERROR (71 on connext): contract not deployed (contractAddress="0x302171031c4fB3cca3395DDb489AC7c0E5Bf5D96", operation="getDeployed", version=4.0.46)
    Error: contract not deployed (contractAddress="0x302171031c4fB3cca3395DDb489AC7c0E5Bf5D96", operation="getDeployed", version=4.0.46)
        at Object.throwError (/app/node_modules/ethers/errors.js:76:17)
        at /app/node_modules/ethers/contract.js:353:32
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async Promise.all (index 0)
[1591087873956] ERROR (71 on connext): contract not deployed (contractAddress="0xc3d29467bfe09d061764F2D841FeD98fBF23c088", operation="getDeployed", version=4.0.46)
    Error: contract not deployed (contractAddress="0xc3d29467bfe09d061764F2D841FeD98fBF23c088", operation="getDeployed", version=4.0.46)
        at Object.throwError (/app/node_modules/ethers/errors.js:76:17)
        at /app/node_modules/ethers/contract.js:353:32
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async Promise.all (index 0)
```

**Comment by raladev** [comment]
Closed, not reproduced with current xud/connext versions.

**Comment by raladev** [comment]
Reproduced this today with combine installation.

connext_block log contains connext logs and xucli calls.

[connext_block.log](https://github.com/ExchangeUnion/xud/files/4885342/connext_block.log)
[xud_block.log](https://github.com/ExchangeUnion/xud/files/4885343/xud_block.log)


[Screen](https://user-images.githubusercontent.com/29906866/86794716-7aabaf80-c075-11ea-9116-94340c69b56f.png)
[Screen](https://user-images.githubusercontent.com/29906866/86794721-7b444600-c075-11ea-8daa-4f0bd0b0b978.png)

**Comment by kilrau** [comment]
Looks like this also prevents xud from shutting down gracefully.
