### ISSUE TITLE
closechannel throws connext server error

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#1690]
```
testnet > getbalance

Balance:
┌──────────┬───────────────┬────────────────────────────┬───────────────────────────────┐
│ Currency │ Total Balance │ Channel Balance (Tradable) │ Wallet Balance (Not Tradable) │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ BTC      │ 0.01750435    │ 0.01462272                 │ 0.00288163                    │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ ETH      │ 18.74995634   │ 5                          │ 13.74995634                   │
├──────────┼───────────────┼────────────────────────────┼───────────────────────────────┤
│ LTC      │ 5.0198001     │ 0                          │ 0.0996945 (4.9201056 pending) │
└──────────┴───────────────┴────────────────────────────┴───────────────────────────────┘
testnet > closechannel eth
Error: 2 UNKNOWN: connext server error
```

connext logs
```
[1593168737424] INFO  (70 on connext): received request
    reqId: 44
    url: "/withdraw"
    id: 44
2020-06-26T10:52:17.428Z [WithdrawalController] withdraw started: {
  "recipient": "",
  "amount": "5000000000000000000"
}
2020-06-26T10:52:17.430Z [WithdrawalController] Creating withdraw commitment
2020-06-26T10:52:17.431Z [CF-GetStateChannel] Executing with params: {"multisigAddress":"0x7571..1E77"}
2020-06-26T10:52:17.442Z [CF-GetStateChannel] Before execution complete in 11 ms
2020-06-26T10:52:17.448Z [CF-GetStateChannel] Executed method implementation in 6 ms
2020-06-26T10:52:17.448Z [CF-GetStateChannel] After execution complete in 0 ms
2020-06-26T10:52:17.449Z [CF-GetStateChannel] Finished executing with result: {"data":{"addresses":{"Token":"0x1665..4a6C","SAIToken":"0xFab4..0136","DepositApp":"0x7333..3A87","IdentityApp":"0xb3B4..eB1c","WithdrawApp":"0x432c..1856","ProxyFactory":"0xe6f2..f426","ChallengeRegistry":"0x44E1..5098","HashLockTransferApp":"0x5f95..680F","FastSignedTransferApp":"0xB377..A2e2","MinimumViableMultisig":"0x8C14..fa85","SimpleTwoPartySwapApp":"0x8cCc..480C","TimeLockedPassThrough":"0x6ac1..6D01","SimpleLinkedTransferApp":"0x5912..086A","SimpleSignedTransferApp":"0xfbc3..4Ee9","TwoPartyFixedOutcomeInterpreter":"0xfC30..B99b","ConditionalTransactionDelegateTarget":"0x0a6C..bEdB","SingleAssetTwoPartyCoinTransferInterpreter":"0xE8C7..3A39","MultiAssetMultiPartyCoinTransferInterpreter":"0x966f..E10d","TwoPartyFixedOutcomeFromVirtualAppInterpreter":"0xaeD5..CF3D"},"appInstances":[["0xec5a..ba4b",{"appDefinition":"0x64eD..b9e2","abiEncodings":{"stateEncoding":"tuple( tuple( address to, uint256 amount)[2] coinTransfers, bytes32 lockHash, bytes32 preImage, uint256 expiry, bool finalized)","actionEncoding":"tuple( bytes32 preImage)"},"appSeqNo":7,"defaultTimeout":"0x215c","identityHash":"0xec5a..ba4b","latestState":{"expiry":"6733318","lockHash":"0x4a0a..cd4f","preImage":"0x0000..0000","finalized":false,"coinTransfers":[{"to":"0xeBF1..DaBC","amount":"38770000000000"},{"to":"0xfC01..62a2","amount":"0"}]},"stateTimeout":"0x00","latestVersionNumber":1,"multisigAddress":"0x7571..1E77","outcomeType":"SINGLE_ASSET_TWO_PARTY_COIN_TRANSFER","initiatorIdentifier":"indra7qWn..Ws3p","responderIdentifier":"indra8gPH..LUhn","outcomeInterpreterParameters":{"limit":"115792089237316195423570985008687907853269984665640564039457584007913129639935","tokenAddress":"0x0000..0000"},"meta":{"sender":"indra7NFT..argJ","timelock":"200","paymentId":"0x8cfc..f51d","recipient":"indra8gPH..LUhn"},"initiatorDeposit":"38770000000000","initiatorDepositAssetId":"0x0000..0000","responderDeposit":"0","responderDepositAssetId":"0x0000..0000"}]],"freeBalanceAppInstance":{"appDefinition":"0xb3B4..eB1c","abiEncodings":{"stateEncoding":"tuple(address[] tokenAddresses, tuple(address to, uint256 amount)[][] balances, bytes32[] activeApps)","actionEncoding":null},"appSeqNo":1,"defaultTimeout":"0x21c0","identityHash":"0x2be7..b487","latestState":{"balances":[[{"to":"0xeBF1..DaBC","amount":"50000000000000000"},{"to":"0xfC01..62a2","amount":"5000000000000000000"}]],"activeApps":["0xec5a..ba4b"],"tokenAddresses":["0x0000..0000"]},"stateTimeout":"0x00","latestVersionNumber":24,"multisigAddress":"0x7571..1E77","outcomeType":"MULTI_ASSET_MULTI_PARTY_COIN_TRANSFER","initiatorIdentifier":"indra7qWn..Ws3p","responderIdentifier":"indra8gPH..LUhn","outcomeInterpreterParameters":{},"meta":null,"initiatorDeposit":"0","initiatorDepositAssetId":"0x0000..0000","responderDeposit":"0","responderDepositAssetId":"0x0000..0000"},"monotonicNumProposedApps":13,"multisigAddress":"0x7571..1E77","proposedAppInstances":[],"schemaVersion":1,"userIdentifiers":["indra7qWn..Ws3p","indra8gPH..LUhn"]}}
2020-06-26T10:52:17.449Z [CF-RpcRouter] Processed chan_getStateChannel method in 18 ms
[1593168737458] ERROR (70 on connext): Error: no matching function (argument="name", value="executeWithdraw", code=INVALID_ARGUMENT, version=abi/5.0.1)
    at Logger.makeError (/app/node_modules/@ethersproject/logger/lib/index.js:179:21)
    at Logger.throwError (/app/node_modules/@ethersproject/logger/lib/index.js:188:20)
    at Logger.throwArgumentError (/app/node_modules/@ethersproject/logger/lib/index.js:191:21)
    at Interface.getFunction (/app/node_modules/@ethersproject/abi/lib/interface.js:176:24)
    at Interface.encodeFunctionData (/app/node_modules/@ethersproject/abi/lib/interface.js:257:37)
    at WithdrawCommitment.getTransactionDetails (/app/node_modules/@connext/apps/dist/index.js:304:85)
    at WithdrawCommitment.encode (/app/node_modules/@connext/contracts/dist/src.ts/commitments/multisig-commitment.js:71:53)
    at WithdrawCommitment.hashToSign (/app/node_modules/@connext/contracts/dist/src.ts/commitments/multisig-commitment.js:82:31)
    at WithdrawalController.<anonymous> (/app/node_modules/@connext/client/dist/controllers/WithdrawalController.js:43:49)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/@connext/client/dist/controllers/WithdrawalController.js:5:58)
    Error: Error: no matching function (argument="name", value="executeWithdraw", code=INVALID_ARGUMENT, version=abi/5.0.1)
        at Logger.makeError (/app/node_modules/@ethersproject/logger/lib/index.js:179:21)
        at Logger.throwError (/app/node_modules/@ethersproject/logger/lib/index.js:188:20)
        at Logger.throwArgumentError (/app/node_modules/@ethersproject/logger/lib/index.js:191:21)
        at Interface.getFunction (/app/node_modules/@ethersproject/abi/lib/interface.js:176:24)
        at Interface.encodeFunctionData (/app/node_modules/@ethersproject/abi/lib/interface.js:257:37)
        at WithdrawCommitment.getTransactionDetails (/app/node_modules/@connext/apps/dist/index.js:304:85)
        at WithdrawCommitment.encode (/app/node_modules/@connext/contracts/dist/src.ts/commitments/multisig-commitment.js:71:53)
        at WithdrawCommitment.hashToSign (/app/node_modules/@connext/contracts/dist/src.ts/commitments/multisig-commitment.js:82:31)
        at WithdrawalController.<anonymous> (/app/node_modules/@connext/client/dist/controllers/WithdrawalController.js:43:49)
        at Generator.next (<anonymous>)
        at fulfilled (/app/node_modules/@connext/client/dist/controllers/WithdrawalController.js:5:58)
        at WithdrawalController.<anonymous> (/app/node_modules/@connext/client/dist/controllers/WithdrawalController.js:84:23)
        at Generator.next (<anonymous>)
        at fulfilled (/app/node_modules/@connext/client/dist/controllers/WithdrawalController.js:5:58)
[1593168737459] INFO  (70 on connext): request completed
    reqId: 44
    url: "/withdraw"
    statusCode: 500
```

**Comment by erkarl** [comment]
Depends on https://github.com/connext/rest-api-client/issues/46

**Comment by kilrau** [comment]
I am a bit confused here: https://github.com/connext/rest-api-client/issues/46 was closed, so what exactly is needed to get `closechannel`/`/withdraw` back? @erkarl @ArjunBhuptani

**Comment by kilrau** [comment]
Should be fixed with alpha.12, let's test again once we upgraded @raladev @erkarl

**Comment by erkarl** [comment]
@raladev you can try with alpha14 https://github.com/ExchangeUnion/xud-docker/pull/587

**Comment by raladev** [comment]
Closed, fixed in alpha 14.
