### ISSUE TITLE
Simulation test failure

### ISSUE THREAD

**Issue by LePremierHomme** [ExchangeUnion/xud#1721]
### Background

CI simulation tests sometimes fail due to different nodes (lnd, xud, etc.) using an already-used port. We use a custom free-port generator, which apparently isn't stable enough. This error results in the node shutdown and the failure of the test. 

### Example

test
```
2020/07/08 06:12:46 xud: launching network...
2020/07/08 06:13:08 cannot start xud network: timeout waiting for xud to be ready
exit status 1
FAIL	github.com/ExchangeUnion/xud-simulation	164.413s
```

xud
```
08/07/2020 06:12:52.167 [GLOBAL] error: Unexpected error during initialization, shutting down...: Error: listen EADDRINUSE: address already in use 127.0.0.1:34365
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1498:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:68:8)
```

**Comment by kilrau** [comment]
Is this still relevant? @LePremierHomme

**Comment by LePremierHomme** [comment]
Closed by https://github.com/ExchangeUnion/xud/pull/1803
