### ISSUE TITLE
xud init error: tls.cert file 

### ISSUE THREAD

**Issue by Chikel** [ExchangeUnion/xud#20]
After installing repo dependencies and running a MySQL instance (+ creating an xud database), 
I receive the following error:

$ ./xud
2018-4-16 13:53:43 info: config loaded
2018-4-16 13:53:43 error: Error: ENOENT: no such file or directory, open '/Users/Chikel/Library/Application Support/Lnd/tls.cert'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at new LndClient (/Users/Chikel/sandbox/xud/lib/lndclient/LndClient.js:18:24)
    at Xud.start (/Users/Chikel/sandbox/xud/lib/Xud.js:35:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

Thanks!

**Comment by moshababo** [comment]
You should either install `lnd` (https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md), or disable its client via your [TOML](https://github.com/toml-lang/toml) `.conf` file. Its expected location is described in our `README.md`, but no example is given yet for this configuration.
You should try to add this:

````
[swapProtocols.LND]
enable = false
````
