### ISSUE TITLE
[Crash] Duplication of host entries from get hosts query in the database

### ISSUE THREAD

**Issue by itsbalamurali** [ExchangeUnion/xud#226]
When XUD (Say Peer1) has previously connected to another XUD (Peer2). Peer2 has Peer1's ip addresses in the hosts table. so during the second time connection between both the peers the hosts data gets exchanged and since peer2 sends the same hosts data to peer1(peer1 table already has it) database is throwing a not unique (`SequelizeUniqueConstraintError`) error.

detailed log:

```bash
> xud@1.0.0-alpha.1 start /home/balamurali_pandranki/xud
> node dist/Xud.js
2018-7-30 19:25:46 [GLOBAL] info: config loaded
Executing (default): SELECT 1+1 AS result
2018-7-30 19:25:47 [DB] info: connected to database. host:******** port:3306 database:xud
2018-7-30 19:25:47 [DB] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `hosts` (`id` INTEGER auto_increment , `address` VARCHAR(39) NOT NULL, `port` INTEGER NOT NULL, `pubKey` VARCHAR(255) UNIQUE, `created
At` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
2018-7-30 19:25:47 [DB] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `bannedHosts` (`address` VARCHAR(39) , `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`address`)) ENGINE=I
nnoDB;
2018-7-30 19:25:47 [DB] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `currencies` (`id` VARCHAR(255) , PRIMARY KEY (`id`)) ENGINE=InnoDB;
2018-7-30 19:25:47 [DB] verbose: Executing (default): SHOW INDEX FROM `hosts`
2018-7-30 19:25:47 [DB] verbose: Executing (default): SHOW INDEX FROM `bannedHosts`
2018-7-30 19:25:47 [DB] verbose: Executing (default): SHOW INDEX FROM `currencies`
2018-7-30 19:25:47 [DB] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `pairs` (`id` VARCHAR(255) , `baseCurrency` VARCHAR(255) NOT NULL, `quoteCurrency` VARCHAR(255) NOT NULL, `swapProtocol` ENUM('LND', '
RAIDEN') NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`baseCurrency`) REFERENCES `currencies` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`quoteCurrency`) REFERENCES `currencies` (`id`) ON DELETE NO ACT
ION ON UPDATE CASCADE) ENGINE=InnoDB;
2018-7-30 19:25:47 [DB] verbose: Executing (default): SHOW INDEX FROM `pairs`
2018-7-30 19:25:47 [LND] error: could not find lnd certificate, is lnd installed?
2018-7-30 19:25:47 [LND] info: LndClient status: DISABLED
Executing (default): SELECT `id`, `address`, `port`, `pubKey`, `createdAt`, `updatedAt` FROM `hosts` AS `Host`;
Executing (default): SELECT `address`, `createdAt`, `updatedAt` FROM `bannedHosts` AS `BannedHost`;
Executing (default): SELECT `id`, `baseCurrency`, `quoteCurrency`, `swapProtocol` FROM `pairs` AS `Pair`;
2018-7-30 19:25:47 [RPC] info: gRPC server listening on localhost:8886
2018-7-30 19:25:47 [P2P] info: p2p server listening on 0.0.0.0:8885
2018-7-30 19:28:45 [P2P] debug: Connected to peer (216.38.151.30:64867)
2018-7-30 19:28:45 [P2P] debug: Received data (216.38.151.30:64867): HELLO {"header":{"hash":"CX8h7aZdVS4/daHcHzyvkw=="},"body":{"version":"123","nodePubKey":"123","listenPort":20000,"pairs":["BTC/LTC"]}}
2018-7-30 19:28:45 [P2P] debug: Received data (216.38.151.30:64867): GET_ORDERS {"header":{"hash":"mZFLkyvTelC5g8XnyQrpOw=="},"body":{}}
GET_HOSTS {"header":{"hash":"Vr2O0ewZCBK0RWtFosmEbQ=="},"body":{"ts":1532978925349}}
2018-7-30 19:28:45 [P2P] debug: Received data (216.38.151.30:64867): HOSTS {"header":{"reqHash":"hgWveqDL/OuWkhs/JjpxzA==","hash":"HfKWilOYL2w01WRkMIh3lg=="},"body":{"hosts":[{"instance":{"id":1,"address":"localhost
","port":8886,"pubKey":null,"createdAt":"2018-07-28T06:38:31.000Z","updatedAt":"2018-07-28T06:38:31.000Z"},"socketAddress":{"address":"localhost","port":8886}},{"instance":{"id":2,"address":"35.196.118.79","port":88
85,"pubKey":null,"createdAt":"2018-07-30T18:36:39.000Z","updatedAt":"2018-07-30T18:36:39.000Z"},"socketAddress":{"address":"35.196.118.79","port":8885}}]}}
ORDERS {"header":{"hash":"sLrRmEfx3k9eLlkpWRUyQg=="},"body":{"orders":[]}}
2018-7-30 19:28:45 [P2P] debug: Peer (216.38.151.30:64867) sent an unsolicited response packet (ORDERS)
2018-7-30 19:28:45 [P2P] debug: Connected to peer ([object Object])
2018-7-30 19:28:45 [P2P] debug: Ignoring banned peer (35.196.118.79)
2018-7-30 19:28:45 [P2P] debug: Connected to peer ([object Object])
2018-7-30 19:28:45 [P2P] debug: Socket Error ([object Object]): Error: read ECONNRESET
2018-7-30 19:28:45 [P2P] error: peer error Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TCP.onread (net.js:618:25)
2018-7-30 19:28:45 [P2P] warn: disconnected peer ([object Object]) hostId is missing
2018-7-30 19:28:45 [P2P] debug: Received data ([object Object]): ?@@ �?
2018-7-30 19:28:45 [P2P] warn: Unknown peer message type: ?@@
2018-7-30 19:28:45 [P2P] debug: Socket Error ([object Object]): Socket hangup
2018-7-30 19:28:45 [P2P] error: peer error Error: Socket Error ([object Object]): Socket hangup
    at Peer.error (/home/balamurali_pandranki/xud/dist/p2p/Peer.js:333:36)
    at Socket.socket.once (/home/balamurali_pandranki/xud/dist/p2p/Peer.js:277:22)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:557:12)
2018-7-30 19:28:45 [P2P] warn: disconnected peer ([object Object]) hostId is missing
Executing (default): SELECT `id`, `baseCurrency`, `quoteCurrency`, `swapProtocol` FROM `pairs` AS `Pair`;
Executing (default): INSERT INTO `hosts` (`id`,`address`,`port`,`createdAt`,`updatedAt`) VALUES (DEFAULT,'35.196.118.79',8885,'2018-07-30 19:28:45','2018-07-30 19:28:45');
Executing (default): INSERT INTO `hosts` (`id`,`address`,`port`,`createdAt`,`updatedAt`) VALUES (DEFAULT,'localhost',8886,'2018-07-30 19:28:45','2018-07-30 19:28:45');
{ SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/home/balamurali_pandranki/xud/node_modules/sequelize/lib/dialects/mysql/query.js:226:16)
    at Query.handler [as onResult] (/home/balamurali_pandranki/xud/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.Command.execute (/home/balamurali_pandranki/xud/node_modules/mysql2/lib/commands/command.js:30:12)
    at Connection.handlePacket (/home/balamurali_pandranki/xud/node_modules/mysql2/lib/connection.js:502:28)
    at PacketParser.onPacket (/home/balamurali_pandranki/xud/node_modules/mysql2/lib/connection.js:81:16)
    at PacketParser.executeStart (/home/balamurali_pandranki/xud/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/home/balamurali_pandranki/xud/node_modules/mysql2/lib/connection.js:89:29)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
  name: 'SequelizeUniqueConstraintError',
  errors: 
   [ ValidationErrorItem {
       message: 'hosts_address_port must be unique',
       type: 'unique violation',
       path: 'hosts_address_port',
       value: '35.196.118.79-8885',
       origin: 'DB',
       instance: [Object],
       validatorKey: 'not_unique',
       validatorName: null,
       validatorArgs: [] } ],
  fields: { hosts_address_port: '35.196.118.79-8885' },
  parent: 
   { Error: Duplicate entry '35.196.118.79-8885' for key 'hosts_address_port'
    at Packet.asError (/home/balamurali_pandranki/xud/node_modules/mysql2/lib/packets/packet.js:716:13)
    at Query.Command.execute (/home/balamurali_pandranki/xud/node_modules/mysql2/lib/commands/command.js:28:22)
    at Connection.handlePacket (/home/balamurali_pandranki/xud/node_modules/mysql2/lib/connection.js:502:28)
    at PacketParser.onPacket (/home/balamurali_pandranki/xud/node_modules/mysql2/lib/connection.js:81:16)
    at PacketParser.executeStart (/home/balamurali_pandranki/xud/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/home/balamurali_pandranki/xud/node_modules/mysql2/lib/connection.js:89:29)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
     code: 'ER_DUP_ENTRY',
     errno: 1062,
     sqlState: '23000',
     sqlMessage: 'Duplicate entry \'35.196.118.79-8885\' for key \'hosts_address_port\'',
     sql: 'INSERT INTO `hosts` (`id`,`address`,`port`,`createdAt`,`updatedAt`) VALUES (DEFAULT,\'35.196.118.79\',8885,\'2018-07-30 19:28:45\',\'2018-07-30 19:28:45\');' },
  original: 
   { Error: Duplicate entry '35.196.118.79-8885' for key 'hosts_address_port'
    at Packet.asError (/home/balamurali_pandranki/xud/node_modules/mysql2/lib/packets/packet.js:716:13)
    at Query.Command.execute (/home/balamurali_pandranki/xud/node_modules/mysql2/lib/commands/command.js:28:22)
    at Connection.handlePacket (/home/balamurali_pandranki/xud/node_modules/mysql2/lib/connection.js:502:28)
    at PacketParser.onPacket (/home/balamurali_pandranki/xud/node_modules/mysql2/lib/connection.js:81:16)
    at PacketParser.executeStart (/home/balamurali_pandranki/xud/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/home/balamurali_pandranki/xud/node_modules/mysql2/lib/connection.js:89:29)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
     code: 'ER_DUP_ENTRY',
     errno: 1062,
     sqlState: '23000',
     sqlMessage: 'Duplicate entry \'35.196.118.79-8885\' for key \'hosts_address_port\'',
     sql: 'INSERT INTO `hosts` (`id`,`address`,`port`,`createdAt`,`updatedAt`) VALUES (DEFAULT,\'35.196.118.79\',8885,\'2018-07-30 19:28:45\',\'2018-07-30 19:28:45\');' },
  sql: 'INSERT INTO `hosts` (`id`,`address`,`port`,`createdAt`,`updatedAt`) VALUES (DEFAULT,\'35.196.118.79\',8885,\'2018-07-30 19:28:45\',\'2018-07-30 19:28:45\');' }
/home/balamurali_pandranki/xud/dist/bootstrap.js:13
        throw err;
        ^

SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/home/balamurali_pandranki/xud/node_modules/sequelize/lib/dialects/mysql/query.js:226:16)
    at Query.handler [as onResult] (/home/balamurali_pandranki/xud/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.Command.execute (/home/balamurali_pandranki/xud/node_modules/mysql2/lib/commands/command.js:30:12)
    at Connection.handlePacket (/home/balamurali_pandranki/xud/node_modules/mysql2/lib/connection.js:502:28)
    at PacketParser.onPacket (/home/balamurali_pandranki/xud/node_modules/mysql2/lib/connection.js:81:16)
    at PacketParser.executeStart (/home/balamurali_pandranki/xud/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/home/balamurali_pandranki/xud/node_modules/mysql2/lib/connection.js:89:29)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xud@1.0.0-alpha.1 start: `node dist/Xud.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xud@1.0.0-alpha.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by kilrau** [comment]
unhandled database error, lead to XUD crash
