### ISSUE TITLE
[Crash] placeOrder with Invalid pairID

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#229]
Current Behavior: placeOrder with Invalid pairID causes XUD to crash, due to unhandled gRPC error
How it should be: gracefully handle all gRPC errors

```
2018-7-30 13:37:14 [RPC] error: invalid pairId: BTC/LTC
TypeError: Incorrectly typed arguments to startBatch
    at handleError (/home/kilrau/xud/node_modules/grpc/src/server.js:71:8)
    at sendUnaryData (/home/kilrau/xud/node_modules/grpc/src/server.js:597:9)
    at GrpcService.<anonymous> (/home/kilrau/xud/dist/grpc/GrpcService.js:40:17)
    at Generator.throw (<anonymous>)
    at rejected (/home/kilrau/xud/dist/grpc/GrpcService.js:5:65)
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
/home/kilrau/xud/dist/bootstrap.js:13
        throw err;
        ^

TypeError: Incorrectly typed arguments to startBatch
    at handleError (/home/kilrau/xud/node_modules/grpc/src/server.js:71:8)
    at sendUnaryData (/home/kilrau/xud/node_modules/grpc/src/server.js:597:9)
    at GrpcService.<anonymous> (/home/kilrau/xud/dist/grpc/GrpcService.js:40:17)
    at Generator.throw (<anonymous>)
    at rejected (/home/kilrau/xud/dist/grpc/GrpcService.js:5:65)
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xud@1.0.0-alpha.1 start: `node dist/Xud.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xud@1.0.0-alpha.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kilrau/.npm/_logs/2018-07-30T20_37_14_899Z-debug.log
```

[2018-07-30T20_37_14_899Z-debug.log](https://github.com/ExchangeUnion/xud/files/2242807/2018-07-30T20_37_14_899Z-debug.log)

**Comment by kilrau** [comment]
Bypassing (hardcoding pairID into matching engine+order book) this leads to:

```
kilrau@ubuntu:~/xud/bin$ ./xucli getorders
{ Error: 2 UNKNOWN: Cannot read property 'buyOrders' of undefined
    at Object.exports.createStatusError (/home/kilrau/xud/node_modules/grpc/src/common.js:87:15)
    at Object.onReceiveStatus (/home/kilrau/xud/node_modules/grpc/src/client_interceptors.js:1214:28)
    at InterceptingListener._callNext (/home/kilrau/xud/node_modules/grpc/src/client_interceptors.js:590:42)
    at InterceptingListener.onReceiveStatus (/home/kilrau/xud/node_modules/grpc/src/client_interceptors.js:640:8)
    at callback (/home/kilrau/xud/node_modules/grpc/src/client_interceptors.js:867:24)
  code: 2,
  metadata: Metadata { _internal_repr: {} },
  details: 'Cannot read property \'buyOrders\' of undefined' }
```

**Comment by kilrau** [comment]
crash is fixed :)

but

`./xucli placeorder LTC/BTC 1 100`
 still leads to
`Error: 5 NOT_FOUND: invalid pairId: LTC/BTC`
whereas

`./xucli placeorder 1 1 100`

works.

**Comment by sangaman** [comment]
@kilrau What happens if you run `getpairs`?

**Comment by sangaman** [comment]
I'm actually unable to reproduce the `./xucli placeorder 1 1 100` error using the current master. Let me know if you're still getting that @kilrau.

**Comment by kilrau** [comment]
As tested earlier, it's magically fixed. I'll reopen if I can reliably reproduce this.
