### ISSUE TITLE
xucli placeorder error

### ISSUE THREAD

**Issue by yyy999** [ExchangeUnion/xud#23]
i just run  ./xucli placeorder --price 0.12 --quantity 5
{ message: 'Cannot read property \'addInvoice\' of undefined',
  code: -32000 }

the server error stack trace is:
RPC server request: {"jsonrpc":"2.0","params":{"order":{"price":0.12,"quantity":5}},"method":"placeOrder","id":1}
2018-4-17 03:17:05 error: RPC server request (1) error TypeError: Cannot read property 'addInvoice' of undefined
    at RpcMethods.placeOrder (/home/sky/xud/lib/rpcserver/RpcMethods.js:63:42)
    at RpcServer.processRequest (/home/sky/xud/node_modules/http-jsonrpc-server/lib/http-jsonrpc-server.js:169:77)
    at IncomingMessage.req.on.on (/home/sky/xud/node_modules/http-jsonrpc-server/lib/reqhandler.js:107:12)
    at IncomingMessage.emit (events.js:180:13)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)

how to solve it ?

**Comment by moshababo** [comment]
The error message is problematic, and will be fixed.
But it seems to happen because LND is disabled.

Did you disable it via the TOML configuration file?

**Comment by DanRui** [comment]
@moshababo After I fetch the latest commit, I install the code and run ./xud , the error message is blow:
2018-4-18 06:43:30 info: config loaded
2018-4-18 06:43:30 error: Error: ENOENT: no such file or directory, open '/home/dr/.lnd/tls.cert'
    at Object.fs.openSync (fs.js:667:18)
    at Object.fs.readFileSync (fs.js:572:33)
    at new LndClient (/home/dr/xud/lib/lndclient/LndClient.js:26:26)
    at Xud.start (/home/dr/xud/lib/Xud.js:33:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
    at Function.Module.runMain (module.js:692:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3

Does I need config something ?
thanks.

**Comment by moshababo** [comment]
@DanRui,
See Issue #20
