### ISSUE TITLE
npm run db:init fails

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#252]
```
kilrau@ubuntu:~/xud$ npm run db:init

> xud@1.0.0-alpha.1 db:init /home/kilrau/xud
> gulp db.init

[23:28:08] Requiring external module ts-node/register
[23:28:10] Using gulpfile ~/xud/gulpfile.ts
[23:28:10] Starting 'db.init'...
Executing (default): SELECT 1+1 AS result
8/1/2018, 11:28:11 PM [DB] info: connected to database. host:localhost port:3306 database:xud_test
8/1/2018, 11:28:11 PM [DB] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `hosts` (`id` INTEGER auto_increment , `address` VARCHAR(39) NOT NULL, `port` INTEGER NOT NULL, `pubKey` VARCHAR(255) UNIQUE, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
8/1/2018, 11:28:11 PM [DB] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `bannedHosts` (`address` VARCHAR(39) , `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`address`)) ENGINE=InnoDB;
8/1/2018, 11:28:11 PM [DB] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `currencies` (`id` VARCHAR(255) , PRIMARY KEY (`id`)) ENGINE=InnoDB;
8/1/2018, 11:28:11 PM [DB] verbose: Executing (default): SHOW INDEX FROM `bannedHosts`
8/1/2018, 11:28:11 PM [DB] verbose: Executing (default): SHOW INDEX FROM `currencies`
8/1/2018, 11:28:11 PM [DB] verbose: Executing (default): SHOW INDEX FROM `hosts`
8/1/2018, 11:28:11 PM [DB] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `pairs` (`id` VARCHAR(255) , `baseCurrency` VARCHAR(255) NOT NULL, `quoteCurrency` VARCHAR(255) NOT NULL, `swapProtocol` ENUM('LND', 'RAIDEN') NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`baseCurrency`) REFERENCES `currencies` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`quoteCurrency`) REFERENCES `currencies` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) ENGINE=InnoDB;
8/1/2018, 11:28:11 PM [DB] verbose: Executing (default): SHOW INDEX FROM `pairs`
Executing (default): INSERT INTO `currencies` (`id`) VALUES ('BTC'),('LTC'),('ZRX'),('GNT');
Executing (default): INSERT INTO `pairs` (`id`,`baseCurrency`,`quoteCurrency`,`swapProtocol`) VALUES ('BTC/LTC','BTC','LTC','LND'),('ZRX/GNT','ZRX','GNT','RAIDEN');
[23:28:11] 'db.init' errored after 993 ms
[23:28:11] SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/home/kilrau/xud/node_modules/sequelize/lib/dialects/mysql/query.js:226:16)
    at Query.handler [as onResult] (/home/kilrau/xud/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.Command.execute (/home/kilrau/xud/node_modules/mysql2/lib/commands/command.js:30:12)
    at Connection.handlePacket (/home/kilrau/xud/node_modules/mysql2/lib/connection.js:502:28)
    at PacketParser.onPacket (/home/kilrau/xud/node_modules/mysql2/lib/connection.js:81:16)
    at PacketParser.executeStart (/home/kilrau/xud/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/home/kilrau/xud/node_modules/mysql2/lib/connection.js:89:29)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:460:23)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:639:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xud@1.0.0-alpha.1 db:init: `gulp db.init`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xud@1.0.0-alpha.1 db:init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kilrau/.npm/_logs/2018-08-02T06_28_11_372Z-debug.log
```

**Comment by kilrau** [comment]
must also be related to PRs today, yesterday it was working.

**Comment by michael1011** [comment]
It is working fine on my machine. Are you sure `pairs` in the database `xud_test` doesn't have any entries when you run it?

Just to make sure you are aware of that: `npm run db:init` is creating and initializing the database `xud_test` which is used for the tests and not for XUD itself as far as I know.

**Comment by kilrau** [comment]
Yep, `xud_test` is successfully setup after running this, but it should be `xud`. Otherwise stuff doesn't work without changing the database via a config file. Default db user is 'xud'. Before this was all the case, so somebody changed it.

Also, before it didn't throw all these errors :/

**Comment by kilrau** [comment]
If database already exists, don't throw errors, just update @itsbalamurali

**Comment by sangaman** [comment]
I'm a bit confused here, @kilrau are you trying to use `db:init` to populate the `xud` db with test data? The `xud` database itself and all the schema gets created when you run xud, even if you've never run `db:init`. It doesn't get populated with any data though.

One thing that is necessary, and that perhaps we should provide instructions for in the README, is a user  with permissions to create databases. By default this user is `xud`, although it can be configured differently. What does your config file look like Kilian? I frequently run `xud` with no config file at all and without having run `db:init`.

**Comment by itsbalamurali** [comment]
@kilrau what @sangaman is saying makes sense totally and i agree with him. `db:init` is only for populating the test database but not for seeding the main one. May be we should update the README to clearly talking about the truncating before you run again the same.

**Comment by kilrau** [comment]
Fine, db:init initializing *xud_test* is ok - I made it a bit clearer via #248
