### ISSUE TITLE
[Crash] on connect

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#253]
latest master, latest p2p-seeding - same behavior:

```
kilrau@ubuntu:~/xud/bin$ ./xud
8/2/2018, 12:18:01 AM [GLOBAL] info: config loaded
Executing (default): SELECT 1+1 AS result
8/2/2018, 12:18:02 AM [DB] info: connected to database. host:localhost port:3306 database:xud
8/2/2018, 12:18:02 AM [DB] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `hosts` (`id` INTEGER auto_increment , `address` VARCHAR(39) NOT NULL, `port` INTEGER NOT NULL, `pubKey` VARCHAR(255) UNIQUE, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
8/2/2018, 12:18:02 AM [DB] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `bannedHosts` (`address` VARCHAR(39) , `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`address`)) ENGINE=InnoDB;
8/2/2018, 12:18:02 AM [DB] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `currencies` (`id` VARCHAR(255) , PRIMARY KEY (`id`)) ENGINE=InnoDB;
8/2/2018, 12:18:02 AM [DB] verbose: Executing (default): SHOW INDEX FROM `hosts`
8/2/2018, 12:18:02 AM [DB] verbose: Executing (default): SHOW INDEX FROM `bannedHosts`
8/2/2018, 12:18:02 AM [DB] verbose: Executing (default): SHOW INDEX FROM `currencies`
8/2/2018, 12:18:02 AM [DB] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `pairs` (`id` VARCHAR(255) , `baseCurrency` VARCHAR(255) NOT NULL, `quoteCurrency` VARCHAR(255) NOT NULL, `swapProtocol` ENUM('LND', 'RAIDEN') NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`baseCurrency`) REFERENCES `currencies` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`quoteCurrency`) REFERENCES `currencies` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) ENGINE=InnoDB;
8/2/2018, 12:18:02 AM [DB] verbose: Executing (default): SHOW INDEX FROM `pairs`
8/2/2018, 12:18:02 AM [LND] error: could not find lnd certificate, is lnd installed?
8/2/2018, 12:18:02 AM [LND] info: LndClient status: DISABLED
8/2/2018, 12:18:02 AM [P2P] info: Connecting to known / previously connected peers
Executing (default): SELECT `id`, `address`, `port`, `pubKey`, `createdAt`, `updatedAt` FROM `hosts` AS `Host`;
Executing (default): SELECT `address`, `createdAt`, `updatedAt` FROM `bannedHosts` AS `BannedHost`;
Executing (default): SELECT `id`, `baseCurrency`, `quoteCurrency`, `swapProtocol` FROM `pairs` AS `Pair`;
8/2/2018, 12:18:02 AM [RPC] info: gRPC server listening on localhost:8886
8/2/2018, 12:18:02 AM [P2P] info: p2p server listening on 0.0.0.0:8885
8/2/2018, 12:18:02 AM [P2P] debug: Connected to peer (xud1.test.exchangeunion.com:8885)
8/2/2018, 12:18:02 AM [P2P] debug: Received data (xud1.test.exchangeunion.com:8885): {"header":{"id":"3176f9f0-9624-11e8-b1a9-9597000142e5","hash":"CX8h7aZdVS4/daHcHzyvkw==","type":"HELLO"},"body":{"version":"123","nodePubKey":"123","listenPort":20000,"pairs":["BTC/LTC"]}}

8/2/2018, 12:18:02 AM [P2P] debug: Received data (xud1.test.exchangeunion.com:8885): {"header":{"id":"317b18a0-9624-11e8-b1a9-9597000142e5","type":"GET_ORDERS"}}
{"header":{"id":"317b3fb0-9624-11e8-b1a9-9597000142e5","type":"GET_HOSTS"}}

Executing (default): SELECT `id`, `baseCurrency`, `quoteCurrency`, `swapProtocol` FROM `pairs` AS `Pair`;
8/2/2018, 12:18:02 AM [P2P] debug: Socket Error (xud1.test.exchangeunion.com:8885): Socket hangup
8/2/2018, 12:18:02 AM [P2P] error: peer error Error: Socket Error (xud1.test.exchangeunion.com:8885): Socket hangup
    at Peer.error (/home/kilrau/xud/dist/p2p/Peer.js:349:36)
    at Socket.socket.once (/home/kilrau/xud/dist/p2p/Peer.js:281:22)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:599:12)
TypeError: Cannot read property 'write' of undefined
    at Peer.sendRaw (/home/kilrau/xud/dist/p2p/Peer.js:124:25)
    at Peer.sendPacket (/home/kilrau/xud/dist/p2p/Peer.js:109:18)
    at Peer.sendOrders (/home/kilrau/xud/dist/p2p/Peer.js:117:18)
    at Promise.all.then (/home/kilrau/xud/dist/orderbook/OrderBook.js:232:22)
/home/kilrau/xud/dist/bootstrap.js:13
        throw err;
        ^

TypeError: Cannot read property 'write' of undefined
    at Peer.sendRaw (/home/kilrau/xud/dist/p2p/Peer.js:124:25)
    at Peer.sendPacket (/home/kilrau/xud/dist/p2p/Peer.js:109:18)
    at Peer.sendOrders (/home/kilrau/xud/dist/p2p/Peer.js:117:18)
    at Promise.all.then (/home/kilrau/xud/dist/orderbook/OrderBook.js:232:22)
```

**Comment by sangaman** [comment]
This is crashing because we expect `socket` to be defined but it is undefined, meaning the actual socket connection was either never created or was destroyed. I've seen it before but not consistently. I'm looking into this.

**Comment by sangaman** [comment]
The logs actually show that `8/2/2018, 12:18:02 AM [P2P] debug: Socket Error (xud1.test.exchangeunion.com:8885): Socket hangup` occurs before the write attempt - we can't write after the socket is closed. It's not clear why the socket was closed in the first place, but we can make sure that we're not attempting to write to a closed socket.
