### ISSUE TITLE
[Crash] duplicate orderid via `./xucli placeorder`

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#257]
Current behavior:
`./xucli placeorder BTC/LTC 1339 100 1` , then again `./xucli placeorder BTC/LTC 1339 100 1` causes `xud` to crash:
```bash
8/2/2018, 12:39:25 PM [RPC] error: duplicated localId: 1339
TypeError: Incorrectly typed arguments to startBatch
    at handleError (/home/kilrau/xud/node_modules/grpc/src/server.js:71:8)
    at sendUnaryData (/home/kilrau/xud/node_modules/grpc/src/server.js:597:9)
    at GrpcService.<anonymous> (/home/kilrau/xud/dist/grpc/GrpcService.js:54:17)
    at Generator.throw (<anonymous>)
    at rejected (/home/kilrau/xud/dist/grpc/GrpcService.js:5:65)
/home/kilrau/xud/dist/bootstrap.js:13
        throw err;
        ^

TypeError: Incorrectly typed arguments to startBatch
    at handleError (/home/kilrau/xud/node_modules/grpc/src/server.js:71:8)
    at sendUnaryData (/home/kilrau/xud/node_modules/grpc/src/server.js:597:9)
    at GrpcService.<anonymous> (/home/kilrau/xud/dist/grpc/GrpcService.js:54:17)
    at Generator.throw (<anonymous>)
    at rejected (/home/kilrau/xud/dist/grpc/GrpcService.js:5:65)
kilrau@ubuntu:~/xud/bin$ 
```

How it should be:
handle the error gracefully and return 'orderId *orderID* already exists'

**Comment by sangaman** [comment]
I think we were aware of this possibility and discussed needing this sort of validation in the PR for local ids, but it looks like we didn't open an issue for it so I will just take care of it now that we have a system in place for grpc error handling.
