### ISSUE TITLE
[Crash] Random 127.0.0.1 added to hosts list, connection leads to crash

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#269]
**Current behavior:**
Running lastest `xud` `master` for a while adds a couple of 127.0.0.1 with different ports to my host list and we don't know where they are coming from. See below. Also interesting: the one finally connected and sending unparsable data doesn't end up in the `hosts` table:

```bash
8/3/2018, 12:18:57 PM [P2P] debug: Received data (xud1.test.exchangeunion.com:8885): {"header":{"reqId":"11ebab10-9752-11e8-b710-bb411fbe5c72","id":"11f23ac0-9752-11e8-9aed-a3a6a4367476","type":"PONG"}}

8/3/2018, 12:19:02 PM [P2P] debug: Connected to peer (127.0.0.1:40118)
8/3/2018, 12:19:02 PM [P2P] debug: Received data (127.0.0.1:40118): 
8/3/2018, 12:19:02 PM [P2P] warn: Unparsable peer message: : SyntaxError: Unexpected token  in JSON at position 0
8/3/2018, 12:19:02 PM [P2P] info: Socket closed (127.0.0.1:40118)
8/3/2018, 12:19:02 PM [P2P] warn: disconnected peer (127.0.0.1:40118) hostId is missing
Error: Peer was destroyed
    at Peer.close (/home/kilrau/xud/dist/p2p/Peer.js:103:30)
    at Socket.socket.once (/home/kilrau/xud/dist/p2p/Peer.js:294:22)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:599:12)
/home/kilrau/xud/dist/bootstrap.js:13
        throw err;
        ^

Error: Peer was destroyed
    at Peer.close (/home/kilrau/xud/dist/p2p/Peer.js:103:30)
    at Socket.socket.once (/home/kilrau/xud/dist/p2p/Peer.js:294:22)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:599:12)
kilrau@ubuntu:~/xud/bin$ mysql -u xud -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 216
Server version: 5.7.23-0ubuntu0.18.04.1 (Ubuntu)

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use xud
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> SELECT * FROM hosts;
+----+-----------------------------+-------+--------+---------------------+---------------------+
| id | address                     | port  | pubKey | createdAt           | updatedAt           |
+----+-----------------------------+-------+--------+---------------------+---------------------+
| 18 | xud1.test.exchangeunion.com |  8885 | NULL   | 2018-08-03 01:27:28 | 2018-08-03 01:27:28 |
| 19 | 0.tcp.ngrok.io              | 19154 | NULL   | 2018-08-03 05:44:44 | 2018-08-03 05:44:44 |
| 20 | 127.0.0.1                   | 37542 | NULL   | 2018-08-03 06:17:46 | 2018-08-03 06:17:46 |
| 21 | 75.75.58.83                 |  8885 | NULL   | 2018-08-03 17:09:15 | 2018-08-03 17:09:15 |
| 22 | 127.0.0.1                   | 39812 | NULL   | 2018-08-03 18:38:50 | 2018-08-03 18:38:50 |
| 23 | 127.0.0.1                   | 39850 | NULL   | 2018-08-03 18:40:15 | 2018-08-03 18:40:15 |
| 24 | 127.0.0.1                   | 39882 | NULL   | 2018-08-03 18:40:15 | 2018-08-03 18:40:15 |
| 25 | 0.tcp.ngrok.io              | 18324 | NULL   | 2018-08-03 18:40:15 | 2018-08-03 18:40:15 |
+----+-----------------------------+-------+--------+---------------------+---------------------+
8 rows in set (0.00 sec)
```
**How it should be:**
there shouldn't be random 127.0.0.1 entries ending up in the hosts table, unparsable data should be handled gracefully. Not connecting to 127.0.0.1 will be dealt with in https://github.com/ExchangeUnion/xud/issues/177

**Comment by kilrau** [comment]
I just deleted all 127.0.0.1 entries and restarted xud. A new 127.0.0.1 entry is shared by a peer and I successfully connect to it:
```bash
kilrau@ubuntu:~/xud/bin$ ./xud
8/3/2018, 12:39:17 PM [GLOBAL] info: config loaded
Executing (default): SELECT 1+1 AS result
8/3/2018, 12:39:17 PM [DB] info: connected to database. host:localhost port:3306 database:xud
8/3/2018, 12:39:17 PM [DB] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `hosts` (`id` INTEGER auto_increment , `address` VARCHAR(39) NOT NULL, `port` INTEGER NOT NULL, `pubKey` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
8/3/2018, 12:39:17 PM [DB] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `bannedHosts` (`address` VARCHAR(39) , `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`address`)) ENGINE=InnoDB;
8/3/2018, 12:39:17 PM [DB] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `currencies` (`id` VARCHAR(255) , PRIMARY KEY (`id`)) ENGINE=InnoDB;
8/3/2018, 12:39:17 PM [DB] verbose: Executing (default): SHOW INDEX FROM `hosts`
8/3/2018, 12:39:17 PM [DB] verbose: Executing (default): SHOW INDEX FROM `bannedHosts`
8/3/2018, 12:39:17 PM [DB] verbose: Executing (default): SHOW INDEX FROM `currencies`
8/3/2018, 12:39:17 PM [DB] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `pairs` (`id` VARCHAR(255) , `baseCurrency` VARCHAR(255) NOT NULL, `quoteCurrency` VARCHAR(255) NOT NULL, `swapProtocol` ENUM('LND', 'RAIDEN') NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`baseCurrency`) REFERENCES `currencies` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`quoteCurrency`) REFERENCES `currencies` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) ENGINE=InnoDB;
8/3/2018, 12:39:17 PM [DB] verbose: Executing (default): SHOW INDEX FROM `pairs`
8/3/2018, 12:39:17 PM [LND] error: could not find lnd certificate, is lnd installed?
8/3/2018, 12:39:17 PM [LND] info: LndClient status: DISABLED
Executing (default): SELECT `id`, `address`, `port`, `pubKey`, `createdAt`, `updatedAt` FROM `hosts` AS `Host`;
Executing (default): SELECT `address`, `createdAt`, `updatedAt` FROM `bannedHosts` AS `BannedHost`;
Executing (default): SELECT `id`, `baseCurrency`, `quoteCurrency`, `swapProtocol` FROM `pairs` AS `Pair`;
8/3/2018, 12:39:17 PM [P2P] info: p2p server listening on 0.0.0.0:8885
8/3/2018, 12:39:17 PM [RPC] info: gRPC server listening on localhost:8886
8/3/2018, 12:39:18 PM [P2P] debug: Connected to peer (0.tcp.ngrok.io:18324)
8/3/2018, 12:39:18 PM [P2P] debug: Connected to peer (127.0.0.1:40404)
8/3/2018, 12:39:18 PM [P2P] debug: Received data (127.0.0.1:40404): {"header":{"id":"e92eb700-9754-11e8-987e-2b759f1f157d","hash":"CX8h7aZdVS4/daHcHzyvkw==","type":"HELLO"},"body":{"version":"123","nodePubKey":"123","listenPort":20000,"pairs":["BTC/LTC"]}}

Executing (default): INSERT INTO `hosts` (`id`,`address`,`port`,`createdAt`,`updatedAt`) VALUES (DEFAULT,'127.0.0.1',40404,'2018-08-03 19:39:18','2018-08-03 19:39:18');
8/3/2018, 12:39:18 PM [P2P] debug: Received data (0.tcp.ngrok.io:18324): {"header":{"id":"e93aec00-9754-11e8-987e-2b759f1f157d","hash":"CX8h7aZdVS4/daHcHzyvkw==","type":"HELLO"},"body":{"version":"123","nodePubKey":"123","listenPort":20000,"pairs":["BTC/LTC"]}}
{"header":{"id":"e93b8840-9754-11e8-987e-2b759f1f157d","type":"GET_ORDERS"}}
{"header":{"id":"e93b8841-9754-11e8-987e-2b759f1f157d","type":"GET_HOSTS"}}

Executing (default): SELECT `id`, `baseCurrency`, `quoteCurrency`, `swapProtocol` FROM `pairs` AS `Pair`;
8/3/2018, 12:39:18 PM [P2P] debug: Received data (127.0.0.1:40404): {"header":{"reqId":"e93b8841-9754-11e8-987e-2b759f1f157d","id":"e95307e0-9754-11e8-987e-2b759f1f157d","hash":"98ZxfKLALsXHKFpM7lgj4g==","type":"HOSTS"},"body":[{"address":"xud1.test.exchangeunion.com","port":8885},{"address":"0.tcp.ngrok.io","port":19154},{"address":"75.75.58.83","port":8885},{"address":"0.tcp.ngrok.io","port":18324},{"address":"127.0.0.1","port":40404}]}

8/3/2018, 12:39:18 PM [P2P] info: Address (0.tcp.ngrok.io) already connected
8/3/2018, 12:39:18 PM [P2P] info: Address (127.0.0.1) already connected
8/3/2018, 12:39:18 PM [P2P] info: Address (0.tcp.ngrok.io) already connected
8/3/2018, 12:39:18 PM [P2P] info: Address (127.0.0.1) already connected
8/3/2018, 12:39:18 PM [P2P] debug: Received data (127.0.0.1:40404): {"header":{"id":"e9532ef0-9754-11e8-987e-2b759f1f157d","type":"GET_ORDERS"}}
{"header":{"id":"e9532ef1-9754-11e8-987e-2b759f1f157d","type":"GET_HOSTS"}}
{"header":{"reqId":"e93b8840-9754-11e8-987e-2b759f1f157d","id":"e9537d10-9754-11e8-987e-2b759f1f157d","hash":"11FxOYiYfpMxmANj4kGJzg==","type":"ORDERS"},"body":[]}

Executing (default): SELECT `id`, `baseCurrency`, `quoteCurrency`, `swapProtocol` FROM `pairs` AS `Pair`;
8/3/2018, 12:39:18 PM [P2P] debug: Received data (0.tcp.ngrok.io:18324): {"header":{"reqId":"e9532ef1-9754-11e8-987e-2b759f1f157d","id":"e96b71e0-9754-11e8-987e-2b759f1f157d","hash":"98ZxfKLALsXHKFpM7lgj4g==","type":"HOSTS"},"body":[{"address":"xud1.test.exchangeunion.com","port":8885},{"address":"0.tcp.ngrok.io","port":19154},{"address":"75.75.58.83","port":8885},{"address":"0.tcp.ngrok.io","port":18324},{"address":"127.0.0.1","port":40404}]}
{"header":{"reqId":"e9532ef0-9754-11e8-987e-2b759f1f157d","id":"e96bc000-9754-11e8-987e-2b759f1f157d","hash":"11FxOYiYfpMxmANj4kGJzg==","type":"ORDERS"},"body":[]}

8/3/2018, 12:39:18 PM [P2P] info: Address (0.tcp.ngrok.io) already connected
8/3/2018, 12:39:18 PM [P2P] info: Address (127.0.0.1) already connected
8/3/2018, 12:39:18 PM [P2P] info: Address (0.tcp.ngrok.io) already connected
8/3/2018, 12:39:18 PM [P2P] info: Address (127.0.0.1) already connected
8/3/2018, 12:39:19 PM [P2P] warn: disconnected peer (0.tcp.ngrok.io:19154) hostId is missing
8/3/2018, 12:39:19 PM [P2P] warn: error while connecting to peer 0.tcp.ngrok.io:19154: Error: connect ECONNREFUSED 52.14.61.47:19154
8/3/2018, 12:39:19 PM [P2P] warn: Socket closed due to error (0.tcp.ngrok.io:19154)
8/3/2018, 12:39:19 PM [P2P] warn: disconnected peer (xud1.test.exchangeunion.com:8885) hostId is missing
8/3/2018, 12:39:19 PM [P2P] warn: error while connecting to peer xud1.test.exchangeunion.com:8885: Error: connect ECONNREFUSED 35.196.118.79:8885
8/3/2018, 12:39:19 PM [P2P] warn: Socket closed due to error (xud1.test.exchangeunion.com:8885)
8/3/2018, 12:39:19 PM [P2P] warn: disconnected peer (xud1.test.exchangeunion.com:8885) hostId is missing
8/3/2018, 12:39:19 PM [P2P] warn: error while connecting to peer xud1.test.exchangeunion.com:8885: Error: connect ECONNREFUSED 35.196.118.79:8885
8/3/2018, 12:39:19 PM [P2P] warn: Socket closed due to error (xud1.test.exchangeunion.com:8885)
8/3/2018, 12:39:19 PM [P2P] warn: disconnected peer (0.tcp.ngrok.io:19154) hostId is missing
8/3/2018, 12:39:19 PM [P2P] warn: error while connecting to peer 0.tcp.ngrok.io:19154: Error: connect ECONNREFUSED 52.14.61.47:19154
8/3/2018, 12:39:19 PM [P2P] warn: Socket closed due to error (0.tcp.ngrok.io:19154)
8/3/2018, 12:39:19 PM [P2P] warn: disconnected peer (xud1.test.exchangeunion.com:8885) hostId is missing
8/3/2018, 12:39:19 PM [P2P] warn: error while connecting to peer xud1.test.exchangeunion.com:8885: Error: connect ECONNREFUSED 35.196.118.79:8885
8/3/2018, 12:39:19 PM [P2P] warn: Socket closed due to error (xud1.test.exchangeunion.com:8885)
8/3/2018, 12:39:19 PM [P2P] warn: disconnected peer (0.tcp.ngrok.io:19154) hostId is missing
8/3/2018, 12:39:19 PM [P2P] warn: error while connecting to peer 0.tcp.ngrok.io:19154: Error: connect ECONNREFUSED 52.14.61.47:19154
8/3/2018, 12:39:19 PM [P2P] warn: Socket closed due to error (0.tcp.ngrok.io:19154)
8/3/2018, 12:39:27 PM [P2P] warn: disconnected peer (75.75.58.83:8885) hostId is missing
8/3/2018, 12:39:27 PM [P2P] warn: error while connecting to peer 75.75.58.83:8885: Error: Connection timed out.
8/3/2018, 12:39:27 PM [P2P] info: Socket closed (75.75.58.83:8885)
8/3/2018, 12:39:28 PM [P2P] warn: disconnected peer (75.75.58.83:8885) hostId is missing
8/3/2018, 12:39:28 PM [P2P] warn: error while connecting to peer 75.75.58.83:8885: Error: Connection timed out.
8/3/2018, 12:39:28 PM [P2P] info: Socket closed (75.75.58.83:8885)
8/3/2018, 12:39:28 PM [P2P] warn: disconnected peer (75.75.58.83:8885) hostId is missing
8/3/2018, 12:39:28 PM [P2P] warn: error while connecting to peer 75.75.58.83:8885: Error: Connection timed out.
8/3/2018, 12:39:28 PM [P2P] info: Socket closed (75.75.58.83:8885)
8/3/2018, 12:39:48 PM [P2P] debug: Received data (0.tcp.ngrok.io:18324): {"header":{"id":"fb1d0430-9754-11e8-987e-2b759f1f157d","type":"PING"}}

8/3/2018, 12:39:48 PM [P2P] debug: Received data (127.0.0.1:40404): {"header":{"id":"fb34d1f0-9754-11e8-987e-2b759f1f157d","type":"PING"}}

8/3/2018, 12:39:48 PM [P2P] debug: Received data (127.0.0.1:40404): {"header":{"reqId":"fb1d0430-9754-11e8-987e-2b759f1f157d","id":"fb356e30-9754-11e8-987e-2b759f1f157d","type":"PONG"}}

8/3/2018, 12:39:48 PM [P2P] debug: Received data (0.tcp.ngrok.io:18324): {"header":{"reqId":"fb34d1f0-9754-11e8-987e-2b759f1f157d","id":"fb415510-9754-11e8-987e-2b759f1f157d","type":"PONG"}}

8/3/2018, 12:40:18 PM [P2P] debug: Received data (0.tcp.ngrok.io:18324): {"header":{"id":"0cfece40-9755-11e8-987e-2b759f1f157d","type":"PING"}}

8/3/2018, 12:40:18 PM [P2P] debug: Received data (127.0.0.1:40404): {"header":{"id":"0d16c310-9755-11e8-987e-2b759f1f157d","type":"PING"}}

8/3/2018, 12:40:18 PM [P2P] debug: Received data (127.0.0.1:40404): {"header":{"reqId":"0cfece40-9755-11e8-987e-2b759f1f157d","id":"0d171130-9755-11e8-987e-2b759f1f157d","type":"PONG"}}

8/3/2018, 12:40:18 PM [P2P] debug: Received data (0.tcp.ngrok.io:18324): {"header":{"reqId":"0d16c310-9755-11e8-987e-2b759f1f157d","id":"0d22f810-9755-11e8-987e-2b759f1f157d","type":"PONG"}}

8/3/2018, 12:40:48 PM [P2P] debug: Received data (0.tcp.ngrok.io:18324): {"header":{"id":"1ee09850-9755-11e8-987e-2b759f1f157d","type":"PING"}}

8/3/2018, 12:40:48 PM [P2P] debug: Received data (127.0.0.1:40404): {"header":{"id":"1ef86610-9755-11e8-987e-2b759f1f157d","type":"PING"}}

8/3/2018, 12:40:48 PM [P2P] debug: Received data (127.0.0.1:40404): {"header":{"reqId":"1ee09850-9755-11e8-987e-2b759f1f157d","id":"1ef8db40-9755-11e8-987e-2b759f1f157d","type":"PONG"}}

8/3/2018, 12:40:48 PM [P2P] debug: Received data (0.tcp.ngrok.io:18324): {"header":{"reqId":"1ef86610-9755-11e8-987e-2b759f1f157d","id":"1f049b10-9755-11e8-987e-2b759f1f157d","type":"PONG"}}
```

**Comment by kilrau** [comment]
deleting hosts and not being connected to any peer stops this behavior

**Comment by kilrau** [comment]
ok, it somehow got todo with the ngrok service (web interface), thus not that urgent --> alpha

```
Session Status                online                                                                            
Account                       Kilian Rausch ⚡ ️    (Plan: Free)                                                 
Version                       2.2.8                                                                             
Region                        United States (us)                                                                
Web Interface                 http://127.0.0.1:4040                                                             
Forwarding                    tcp://0.tcp.ngrok.io:15761 -> localhost:8885                                      
                                                                                                                
Connections                   ttl     opn     rt1     rt5     p50     p90                                       
                              0       0       0.00    0.00    0.00    0.00 
```

**Comment by sangaman** [comment]
This is expected (but undesirable) behavior until we properly advertise external IP and listening port to other peers. I'll take care of this as part of the host/peer restructuring discussed in #185.
