### ISSUE TITLE
Order matching doesn't work

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud#276]
I mentioned this [here](https://github.com/ExchangeUnion/xud/pull/244#issuecomment-410115395) before, matching doesn't work. First order (xud1) goes thru, second order (xud2) throws:

```
kilrau@ubuntu:~/xud/bin$ ./xucli -p 54322 placeorder BTC/LTC 1 1 99
(node:6225) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Error: 2 UNKNOWN: Cannot read property 'quantity' of undefined
```
```
8/3/2018, 4:43:22 PM [ORDERBOOK] debug: order match: {"maker":{"price":99,"quantity":-1,"pairId":"BTC/LTC","peerId":0,"hostId":4,"id":"ddeafc60-9776-11e8-9485-d51bda3e6ac4","invoice":"dummyInvoice","createdAt":1533339741996},"taker":{"price":99,"quantity":1,"pairId":"BTC/LTC","peerId":0,"hostId":"","id":"02234b50-9777-11e8-a286-430dcc42b522","localId":"1","createdAt":1533339802757,"invoice":""}}
8/3/2018, 4:43:22 PM [RPC] error: TypeError: Cannot read property 'quantity' of undefined
    at OrderBook.updateOrderQuantity (/home/kilrau/xud/dist/orderbook/OrderBook.js:182:62)
    at matches.forEach (/home/kilrau/xud/dist/orderbook/OrderBook.js:151:26)
    at Array.forEach (<anonymous>)
    at OrderBook.addOwnOrder (/home/kilrau/xud/dist/orderbook/OrderBook.js:149:25)
    at OrderBook.addLimitOrder (/home/kilrau/xud/dist/orderbook/OrderBook.js:94:25)
    at Service.<anonymous> (/home/kilrau/xud/dist/service/Service.js:132:53)
    at Generator.next (<anonymous>)
    at /home/kilrau/xud/dist/service/Service.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/kilrau/xud/dist/service/Service.js:3:12)
    at Service.placeOrder (/home/kilrau/xud/dist/service/Service.js:129:38)
    at GrpcService.<anonymous> (/home/kilrau/xud/dist/grpc/GrpcService.js:38:43)
    at Generator.next (<anonymous>)
    at /home/kilrau/xud/dist/grpc/GrpcService.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/kilrau/xud/dist/grpc/GrpcService.js:3:12)
    at GrpcService.unaryCall (/home/kilrau/xud/dist/grpc/GrpcService.js:36:61)
    at GrpcService.<anonymous> (/home/kilrau/xud/dist/grpc/GrpcService.js:84:18)
    at Generator.next (<anonymous>)
    at /home/kilrau/xud/dist/grpc/GrpcService.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/kilrau/xud/dist/grpc/GrpcService.js:3:12)

```
Nothing received on xud1. No difference if buy or sell first. Current master.

**Comment by kilrau** [comment]
Then when xud is running for a while it magically starts working. Here the complete output of xud2 repeatedly failing to place the order with above ouput, then at one it goes thru"

```bash
kilrau@ubuntu:~/xud/bin$ ./xud -p 54321 -r 54322 --db.database xud_test
8/3/2018, 5:05:40 PM [GLOBAL] info: config loaded
Executing (default): SELECT 1+1 AS result
8/3/2018, 5:05:40 PM [DB] info: connected to database. host:localhost port:3306 database:xud_test
8/3/2018, 5:05:40 PM [DB] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `hosts` (`id` INTEGER auto_increment , `address` VARCHAR(39) NOT NULL, `port` INTEGER NOT NULL, `pubKey` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
8/3/2018, 5:05:40 PM [DB] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `bannedHosts` (`address` VARCHAR(39) , `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`address`)) ENGINE=InnoDB;
8/3/2018, 5:05:40 PM [DB] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `currencies` (`id` VARCHAR(255) , PRIMARY KEY (`id`)) ENGINE=InnoDB;
8/3/2018, 5:05:40 PM [DB] verbose: Executing (default): SHOW INDEX FROM `hosts`
8/3/2018, 5:05:40 PM [DB] verbose: Executing (default): SHOW INDEX FROM `bannedHosts`
8/3/2018, 5:05:40 PM [DB] verbose: Executing (default): SHOW INDEX FROM `currencies`
8/3/2018, 5:05:40 PM [DB] verbose: Executing (default): CREATE TABLE IF NOT EXISTS `pairs` (`id` VARCHAR(255) , `baseCurrency` VARCHAR(255) NOT NULL, `quoteCurrency` VARCHAR(255) NOT NULL, `swapProtocol` ENUM('LND', 'RAIDEN') NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`baseCurrency`) REFERENCES `currencies` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`quoteCurrency`) REFERENCES `currencies` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) ENGINE=InnoDB;
8/3/2018, 5:05:40 PM [DB] verbose: Executing (default): SHOW INDEX FROM `pairs`
8/3/2018, 5:05:40 PM [LND] error: could not find lnd certificate, is lnd installed?
8/3/2018, 5:05:40 PM [LND] info: LndClient status: DISABLED
Executing (default): SELECT `id`, `address`, `port`, `pubKey`, `createdAt`, `updatedAt` FROM `hosts` AS `Host`;
Executing (default): SELECT `address`, `createdAt`, `updatedAt` FROM `bannedHosts` AS `BannedHost`;
Executing (default): SELECT `id`, `baseCurrency`, `quoteCurrency`, `swapProtocol` FROM `pairs` AS `Pair`;
8/3/2018, 5:05:40 PM [P2P] info: p2p server listening on 0.0.0.0:54321
8/3/2018, 5:05:40 PM [P2P] warn: disconnected peer (127.0.0.1:40916) hostId is missing
8/3/2018, 5:05:40 PM [P2P] warn: error while connecting to peer 127.0.0.1:40916: Error: connect ECONNREFUSED 127.0.0.1:40916
8/3/2018, 5:05:40 PM [P2P] warn: disconnected peer (127.0.0.1:40934) hostId is missing
8/3/2018, 5:05:40 PM [P2P] warn: error while connecting to peer 127.0.0.1:40934: Error: connect ECONNREFUSED 127.0.0.1:40934
8/3/2018, 5:05:40 PM [P2P] warn: Socket closed due to error (127.0.0.1:40934)
8/3/2018, 5:05:40 PM [P2P] warn: Socket closed due to error (127.0.0.1:40916)
8/3/2018, 5:05:40 PM [P2P] debug: Connected to peer (127.0.0.1:40962)
8/3/2018, 5:05:40 PM [P2P] warn: disconnected peer (localhost:1234) hostId is missing
8/3/2018, 5:05:40 PM [P2P] warn: error while connecting to peer localhost:1234: Error: connect ECONNREFUSED 127.0.0.1:1234
8/3/2018, 5:05:40 PM [P2P] debug: Connected to peer (localhost:54321)
8/3/2018, 5:05:40 PM [RPC] info: gRPC server listening on localhost:54322
8/3/2018, 5:05:40 PM [P2P] warn: Socket closed due to error (localhost:1234)
8/3/2018, 5:05:40 PM [P2P] debug: Received data (localhost:54321): {"header":{"id":"1fbd15d0-977a-11e8-a600-1907c9c06d11","hash":"CX8h7aZdVS4/daHcHzyvkw==","type":"HELLO"},"body":{"version":"123","nodePubKey":"123","listenPort":20000,"pairs":["BTC/LTC"]}}

8/3/2018, 5:05:40 PM [P2P] debug: Received data (127.0.0.1:40962): {"header":{"id":"1fbdb210-977a-11e8-a600-1907c9c06d11","hash":"CX8h7aZdVS4/daHcHzyvkw==","type":"HELLO"},"body":{"version":"123","nodePubKey":"123","listenPort":20000,"pairs":["BTC/LTC"]}}
{"header":{"id":"1fc727f0-977a-11e8-a600-1907c9c06d11","type":"GET_ORDERS"}}
{"header":{"id":"1fc74f00-977a-11e8-a600-1907c9c06d11","type":"GET_HOSTS"}}

Executing (default): SELECT `id`, `baseCurrency`, `quoteCurrency`, `swapProtocol` FROM `pairs` AS `Pair`;
Executing (default): INSERT INTO `hosts` (`id`,`address`,`port`,`createdAt`,`updatedAt`) VALUES (DEFAULT,'127.0.0.1',40962,'2018-08-04 00:05:40','2018-08-04 00:05:40');
8/3/2018, 5:05:41 PM [P2P] debug: Received data (localhost:54321): {"header":{"reqId":"1fc74f00-977a-11e8-a600-1907c9c06d11","id":"1fc79d20-977a-11e8-a600-1907c9c06d11","hash":"E6ETXe3MyaalYGkEIQuMhA==","type":"HOSTS"},"body":[{"address":"127.0.0.1","port":40916},{"address":"localhost","port":1234},{"address":"localhost","port":54321},{"address":"127.0.0.1","port":40934}]}
{"header":{"id":"1fc7eb40-977a-11e8-a600-1907c9c06d11","type":"GET_ORDERS"}}
{"header":{"id":"1fc7eb41-977a-11e8-a600-1907c9c06d11","type":"GET_HOSTS"}}

8/3/2018, 5:05:41 PM [P2P] info: Address (localhost) already connected
8/3/2018, 5:05:41 PM [P2P] info: Address (localhost) already connected
Executing (default): SELECT `id`, `baseCurrency`, `quoteCurrency`, `swapProtocol` FROM `pairs` AS `Pair`;
8/3/2018, 5:05:41 PM [P2P] debug: Received data (127.0.0.1:40962): {"header":{"reqId":"1fc7eb41-977a-11e8-a600-1907c9c06d11","id":"1fcd6980-977a-11e8-a600-1907c9c06d11","hash":"E6ETXe3MyaalYGkEIQuMhA==","type":"HOSTS"},"body":[{"address":"127.0.0.1","port":40916},{"address":"localhost","port":1234},{"address":"localhost","port":54321},{"address":"127.0.0.1","port":40934}]}

8/3/2018, 5:05:41 PM [P2P] info: Address (localhost) already connected
8/3/2018, 5:05:41 PM [P2P] info: Address (localhost) already connected
8/3/2018, 5:05:41 PM [P2P] warn: disconnected peer (127.0.0.1:40916) hostId is missing
8/3/2018, 5:05:41 PM [P2P] warn: error while connecting to peer 127.0.0.1:40916: Error: connect ECONNREFUSED 127.0.0.1:40916
8/3/2018, 5:05:41 PM [P2P] warn: disconnected peer (127.0.0.1:40934) hostId is missing
8/3/2018, 5:05:41 PM [P2P] warn: error while connecting to peer 127.0.0.1:40934: Error: connect ECONNREFUSED 127.0.0.1:40934
8/3/2018, 5:05:41 PM [P2P] warn: Socket closed due to error (127.0.0.1:40934)
8/3/2018, 5:05:41 PM [P2P] warn: Socket closed due to error (127.0.0.1:40916)
8/3/2018, 5:05:41 PM [P2P] debug: Received data (localhost:54321): {"header":{"reqId":"1fc727f0-977a-11e8-a600-1907c9c06d11","id":"1fcef020-977a-11e8-a600-1907c9c06d11","hash":"11FxOYiYfpMxmANj4kGJzg==","type":"ORDERS"},"body":[]}

8/3/2018, 5:05:41 PM [P2P] warn: disconnected peer (localhost:1234) hostId is missing
8/3/2018, 5:05:41 PM [P2P] warn: error while connecting to peer localhost:1234: Error: connect ECONNREFUSED 127.0.0.1:1234
8/3/2018, 5:05:41 PM [P2P] warn: disconnected peer (127.0.0.1:40916) hostId is missing
8/3/2018, 5:05:41 PM [P2P] warn: error while connecting to peer 127.0.0.1:40916: Error: connect ECONNREFUSED 127.0.0.1:40916
8/3/2018, 5:05:41 PM [P2P] warn: disconnected peer (127.0.0.1:40934) hostId is missing
8/3/2018, 5:05:41 PM [P2P] warn: error while connecting to peer 127.0.0.1:40934: Error: connect ECONNREFUSED 127.0.0.1:40934
8/3/2018, 5:05:41 PM [P2P] warn: Socket closed due to error (127.0.0.1:40934)
8/3/2018, 5:05:41 PM [P2P] warn: Socket closed due to error (127.0.0.1:40916)
8/3/2018, 5:05:41 PM [P2P] warn: Socket closed due to error (localhost:1234)
8/3/2018, 5:05:41 PM [P2P] warn: disconnected peer (localhost:1234) hostId is missing
8/3/2018, 5:05:41 PM [P2P] warn: error while connecting to peer localhost:1234: Error: connect ECONNREFUSED 127.0.0.1:1234
8/3/2018, 5:05:41 PM [P2P] warn: Socket closed due to error (localhost:1234)
8/3/2018, 5:05:41 PM [P2P] debug: Received data (127.0.0.1:40962): {"header":{"reqId":"1fc7eb40-977a-11e8-a600-1907c9c06d11","id":"1fd11300-977a-11e8-a600-1907c9c06d11","hash":"11FxOYiYfpMxmANj4kGJzg==","type":"ORDERS"},"body":[]}

8/3/2018, 5:05:43 PM [P2P] debug: Connected to peer (127.0.0.1:40986)
8/3/2018, 5:05:43 PM [P2P] debug: Received data (127.0.0.1:40986): {"header":{"id":"216324b0-977a-11e8-a829-fbd3bfc132fc","hash":"CX8h7aZdVS4/daHcHzyvkw==","type":"HELLO"},"body":{"version":"123","nodePubKey":"123","listenPort":20000,"pairs":["BTC/LTC"]}}

Executing (default): INSERT INTO `hosts` (`id`,`address`,`port`,`createdAt`,`updatedAt`) VALUES (DEFAULT,'127.0.0.1',40986,'2018-08-04 00:05:43','2018-08-04 00:05:43');
8/3/2018, 5:05:43 PM [P2P] debug: Received data (127.0.0.1:40986): {"header":{"id":"2163c0f0-977a-11e8-a829-fbd3bfc132fc","type":"GET_ORDERS"}}
{"header":{"id":"2163c0f1-977a-11e8-a829-fbd3bfc132fc","type":"GET_HOSTS"}}

Executing (default): SELECT `id`, `baseCurrency`, `quoteCurrency`, `swapProtocol` FROM `pairs` AS `Pair`;
8/3/2018, 5:05:43 PM [P2P] debug: Received data (127.0.0.1:40986): {"header":{"reqId":"216399e1-977a-11e8-a600-1907c9c06d11","id":"2163e800-977a-11e8-a829-fbd3bfc132fc","hash":"bl4xTKddpuGaUhtfh+qymA==","type":"HOSTS"},"body":[{"address":"localhost","port":54321},{"address":"127.0.0.1","port":53234}]}
{"header":{"reqId":"216399e0-977a-11e8-a600-1907c9c06d11","id":"2164d260-977a-11e8-a829-fbd3bfc132fc","hash":"11FxOYiYfpMxmANj4kGJzg==","type":"ORDERS"},"body":[]}

8/3/2018, 5:05:43 PM [P2P] info: Address (localhost) already connected
8/3/2018, 5:05:43 PM [P2P] info: Address (localhost) already connected
8/3/2018, 5:05:43 PM [P2P] warn: disconnected peer (127.0.0.1:53234) hostId is missing
8/3/2018, 5:05:43 PM [P2P] warn: error while connecting to peer 127.0.0.1:53234: Error: connect ECONNREFUSED 127.0.0.1:53234
8/3/2018, 5:05:43 PM [P2P] warn: Socket closed due to error (127.0.0.1:53234)
8/3/2018, 5:05:56 PM [P2P] debug: Received data (127.0.0.1:40986): {"header":{"id":"28db11d0-977a-11e8-a829-fbd3bfc132fc","hash":"945oUwrRud/PFvo5f/raRg==","type":"ORDER"},"body":{"price":99,"quantity":-1,"pairId":"BTC/LTC","peerId":0,"hostId":"","id":"28da9ca0-977a-11e8-a829-fbd3bfc132fc","invoice":"dummyInvoice"}}

8/3/2018, 5:05:56 PM [ORDERBOOK] debug: order added: {"price":99,"quantity":-1,"pairId":"BTC/LTC","peerId":0,"hostId":31,"id":"28da9ca0-977a-11e8-a829-fbd3bfc132fc","invoice":"dummyInvoice","createdAt":1533341156206}
8/3/2018, 5:06:04 PM [ORDERBOOK] debug: order match: {"maker":{"price":99,"quantity":-1,"pairId":"BTC/LTC","peerId":0,"hostId":31,"id":"28da9ca0-977a-11e8-a829-fbd3bfc132fc","invoice":"dummyInvoice","createdAt":1533341156206},"taker":{"price":99,"quantity":1,"pairId":"BTC/LTC","peerId":0,"hostId":"","id":"2db71e60-977a-11e8-a600-1907c9c06d11","localId":"1","createdAt":1533341164358,"invoice":""}}
8/3/2018, 5:06:04 PM [RPC] error: TypeError: Cannot read property 'quantity' of undefined
    at OrderBook.updateOrderQuantity (/home/kilrau/xud/dist/orderbook/OrderBook.js:182:62)
    at matches.forEach (/home/kilrau/xud/dist/orderbook/OrderBook.js:151:26)
    at Array.forEach (<anonymous>)
    at OrderBook.addOwnOrder (/home/kilrau/xud/dist/orderbook/OrderBook.js:149:25)
    at OrderBook.addLimitOrder (/home/kilrau/xud/dist/orderbook/OrderBook.js:94:25)
    at Service.<anonymous> (/home/kilrau/xud/dist/service/Service.js:132:53)
    at Generator.next (<anonymous>)
    at /home/kilrau/xud/dist/service/Service.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/kilrau/xud/dist/service/Service.js:3:12)
    at Service.placeOrder (/home/kilrau/xud/dist/service/Service.js:129:38)
    at GrpcService.<anonymous> (/home/kilrau/xud/dist/grpc/GrpcService.js:38:43)
    at Generator.next (<anonymous>)
    at /home/kilrau/xud/dist/grpc/GrpcService.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/kilrau/xud/dist/grpc/GrpcService.js:3:12)
    at GrpcService.unaryCall (/home/kilrau/xud/dist/grpc/GrpcService.js:36:61)
    at GrpcService.<anonymous> (/home/kilrau/xud/dist/grpc/GrpcService.js:84:18)
    at Generator.next (<anonymous>)
    at /home/kilrau/xud/dist/grpc/GrpcService.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/kilrau/xud/dist/grpc/GrpcService.js:3:12)
8/3/2018, 5:06:10 PM [P2P] debug: Received data (127.0.0.1:40962): {"header":{"id":"31a8caf0-977a-11e8-a600-1907c9c06d11","type":"PING"}}

8/3/2018, 5:06:10 PM [P2P] debug: Received data (localhost:54321): {"header":{"reqId":"31a8caf0-977a-11e8-a600-1907c9c06d11","id":"31a8f200-977a-11e8-a600-1907c9c06d11","type":"PONG"}}

8/3/2018, 5:06:10 PM [P2P] debug: Received data (localhost:54321): {"header":{"id":"31a96730-977a-11e8-a600-1907c9c06d11","type":"PING"}}

8/3/2018, 5:06:10 PM [P2P] debug: Received data (127.0.0.1:40962): {"header":{"reqId":"31a96730-977a-11e8-a600-1907c9c06d11","id":"31a96731-977a-11e8-a600-1907c9c06d11","type":"PONG"}}

8/3/2018, 5:06:13 PM [P2P] debug: Received data (127.0.0.1:40986): {"header":{"id":"334563f0-977a-11e8-a829-fbd3bfc132fc","type":"PING"}}

8/3/2018, 5:06:13 PM [P2P] debug: Received data (127.0.0.1:40986): {"header":{"reqId":"3345b210-977a-11e8-a600-1907c9c06d11","id":"33464e50-977a-11e8-a829-fbd3bfc132fc","type":"PONG"}}

8/3/2018, 5:06:32 PM [P2P] debug: Received data (127.0.0.1:40986): {"header":{"id":"3e405d50-977a-11e8-a829-fbd3bfc132fc","hash":"npkIOJsJT+x832jGtpjavw==","type":"ORDER"},"body":{"price":99,"quantity":-1,"pairId":"BTC/LTC","peerId":0,"hostId":"","id":"3e403640-977a-11e8-a829-fbd3bfc132fc","invoice":"dummyInvoice"}}

8/3/2018, 5:06:32 PM [ORDERBOOK] debug: order added: {"price":99,"quantity":-1,"pairId":"BTC/LTC","peerId":0,"hostId":31,"id":"3e403640-977a-11e8-a829-fbd3bfc132fc","invoice":"dummyInvoice","createdAt":1533341192102}
8/3/2018, 5:06:40 PM [P2P] debug: Received data (127.0.0.1:40962): {"header":{"id":"438a9500-977a-11e8-a600-1907c9c06d11","type":"PING"}}

8/3/2018, 5:06:40 PM [P2P] debug: Received data (localhost:54321): {"header":{"reqId":"438a9500-977a-11e8-a600-1907c9c06d11","id":"438a9501-977a-11e8-a600-1907c9c06d11","type":"PONG"}}

8/3/2018, 5:06:40 PM [P2P] debug: Received data (localhost:54321): {"header":{"id":"438b0a30-977a-11e8-a600-1907c9c06d11","type":"PING"}}

8/3/2018, 5:06:40 PM [P2P] debug: Received data (127.0.0.1:40962): {"header":{"reqId":"438b0a30-977a-11e8-a600-1907c9c06d11","id":"438b0a31-977a-11e8-a600-1907c9c06d11","type":"PONG"}}

8/3/2018, 5:06:41 PM [ORDERBOOK] debug: order match: {"maker":{"price":99,"quantity":-1,"pairId":"BTC/LTC","peerId":0,"hostId":31,"id":"3e403640-977a-11e8-a829-fbd3bfc132fc","invoice":"dummyInvoice","createdAt":1533341192102},"taker":{"price":99,"quantity":1,"pairId":"BTC/LTC","peerId":0,"hostId":"","id":"4400d670-977a-11e8-a600-1907c9c06d11","localId":"2","createdAt":1533341201751,"invoice":""}}
8/3/2018, 5:06:41 PM [RPC] error: TypeError: Cannot read property 'quantity' of undefined
    at OrderBook.updateOrderQuantity (/home/kilrau/xud/dist/orderbook/OrderBook.js:182:62)
    at matches.forEach (/home/kilrau/xud/dist/orderbook/OrderBook.js:151:26)
    at Array.forEach (<anonymous>)
    at OrderBook.addOwnOrder (/home/kilrau/xud/dist/orderbook/OrderBook.js:149:25)
    at OrderBook.addLimitOrder (/home/kilrau/xud/dist/orderbook/OrderBook.js:94:25)
    at Service.<anonymous> (/home/kilrau/xud/dist/service/Service.js:132:53)
    at Generator.next (<anonymous>)
    at /home/kilrau/xud/dist/service/Service.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/kilrau/xud/dist/service/Service.js:3:12)
    at Service.placeOrder (/home/kilrau/xud/dist/service/Service.js:129:38)
    at GrpcService.<anonymous> (/home/kilrau/xud/dist/grpc/GrpcService.js:38:43)
    at Generator.next (<anonymous>)
    at /home/kilrau/xud/dist/grpc/GrpcService.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/kilrau/xud/dist/grpc/GrpcService.js:3:12)
    at GrpcService.unaryCall (/home/kilrau/xud/dist/grpc/GrpcService.js:36:61)
    at GrpcService.<anonymous> (/home/kilrau/xud/dist/grpc/GrpcService.js:84:18)
    at Generator.next (<anonymous>)
    at /home/kilrau/xud/dist/grpc/GrpcService.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/kilrau/xud/dist/grpc/GrpcService.js:3:12)
8/3/2018, 5:06:43 PM [P2P] debug: Received data (127.0.0.1:40986): {"header":{"id":"452706f0-977a-11e8-a829-fbd3bfc132fc","type":"PING"}}

8/3/2018, 5:06:43 PM [P2P] debug: Received data (127.0.0.1:40986): {"header":{"reqId":"45277c20-977a-11e8-a600-1907c9c06d11","id":"4527a330-977a-11e8-a829-fbd3bfc132fc","type":"PONG"}}

8/3/2018, 5:06:57 PM [ORDERBOOK] debug: order added: {"price":99,"quantity":1,"pairId":"BTC/LTC","peerId":0,"hostId":"","id":"4d72bed0-977a-11e8-a600-1907c9c06d11","localId":"2","createdAt":1533341217597,"invoice":""}
8/3/2018, 5:06:57 PM [P2P] debug: Received data (127.0.0.1:40962): {"header":{"id":"4d735b10-977a-11e8-a600-1907c9c06d11","hash":"W1e6sPd3/PDfJBVUp4d0dA==","type":"ORDER"},"body":{"price":99,"quantity":1,"pairId":"BTC/LTC","peerId":0,"hostId":"","id":"4d72bed0-977a-11e8-a600-1907c9c06d11","invoice":"dummyInvoice"}}

8/3/2018, 5:06:57 PM [ORDERBOOK] debug: order added: {"price":99,"quantity":1,"pairId":"BTC/LTC","peerId":0,"hostId":30,"id":"4d72bed0-977a-11e8-a600-1907c9c06d11","invoice":"dummyInvoice","createdAt":1533341217602}
8/3/2018, 5:06:57 PM [P2P] debug: Received data (localhost:54321): {"header":{"id":"4d735b10-977a-11e8-a600-1907c9c06d11","hash":"W1e6sPd3/PDfJBVUp4d0dA==","type":"ORDER"},"body":{"price":99,"quantity":1,"pairId":"BTC/LTC","peerId":0,"hostId":"","id":"4d72bed0-977a-11e8-a600-1907c9c06d11","invoice":"dummyInvoice"}}

8/3/2018, 5:06:57 PM [ORDERBOOK] debug: order added: {"price":99,"quantity":1,"pairId":"BTC/LTC","peerId":0,"hostId":28,"id":"4d72bed0-977a-11e8-a600-1907c9c06d11","invoice":"dummyInvoice","createdAt":1533341217602}
8/3/2018, 5:07:10 PM [P2P] debug: Received data (127.0.0.1:40962): {"header":{"id":"556c5f10-977a-11e8-a600-1907c9c06d11","type":"PING"}}

8/3/2018, 5:07:10 PM [P2P] debug: Received data (localhost:54321): {"header":{"reqId":"556c5f10-977a-11e8-a600-1907c9c06d11","id":"556c5f11-977a-11e8-a600-1907c9c06d11","type":"PONG"}}

8/3/2018, 5:07:10 PM [P2P] debug: Received data (localhost:54321): {"header":{"id":"556cad30-977a-11e8-a600-1907c9c06d11","type":"PING"}}

8/3/2018, 5:07:10 PM [P2P] debug: Received data (127.0.0.1:40962): {"header":{"reqId":"556cad30-977a-11e8-a600-1907c9c06d11","id":"556cd440-977a-11e8-a600-1907c
```

**Comment by moshababo** [comment]
This occurs after a non-internal match, due to bug on OrderBook.ts line 181 - it assumes that it's an internal match, so the maker order lookup fails. Will fix it shortly.

**Comment by moshababo** [comment]
This occurs after a non-internal match, due to bug on OrderBook.ts line 181 - it assumes that it's an internal match, so the maker order lookup fails. Will fix it shortly.
