### ISSUE TITLE
TypeError: Cannot read property 'quantity' of undefined

### ISSUE THREAD

**Issue by liujiafeng622** [ExchangeUnion/xud#310]
node版本：v8.11.2

1、我首先添加了一个订单：order added: {"price":10.22,"quantity":5.9,"pairId":"BTC/LTC","peerId":"","id":"8324aec0-9b6d-11e8-a143-d981a9d556cc","localId":"","createdAt":1533775528876,"invoice":""}
2、我又添加了了一个订单
3、交易引擎match了两个订单：order match: {"maker":{"price":10.22,"quantity":5.9,"pairId":"BTC/LTC","peerId":"","id":"8324aec0-9b6d-11e8-a143-d981a9d556cc","localId":"","createdAt":1533775528876,"invoice":""},"taker":{"price":10.22,"quantity":-5.9,"pairId":"BTC/LTC","peerId":"","id":"4aad7670-9b6e-11e8-a143-d981a9d556cc","localId":"1233","createdAt":1533775863639,"invoice":""}}
4、在match的时候，交易引擎出错了

2018-8-8 20:51:03 [ORDERBOOK] debug: order match: {"maker":{"price":10.22,"quantity":5.9,"pairId":"BTC/LTC","peerId":"","id":"8324aec0-9b6d-11e8-a143-d981a9d556cc","localId":"","createdAt":1533775528876,"invoice":""},"taker":{"price":10.22,"quantity":-5.9,"pairId":"BTC/LTC","peerId":"","id":"4aad7670-9b6e-11e8-a143-d981a9d556cc","localId":"1233","createdAt":1533775863639,"invoice":""}}
2018-8-8 20:51:03 [RPC] error: TypeError: Cannot read property 'quantity' of undefined
    at OrderBook.updateOrderQuantity (/home/stephen/Desktop/xud-1.0.0-prealpha.1/dist/orderbook/OrderBook.js:182:62)
    at matches.forEach (/home/stephen/Desktop/xud-1.0.0-prealpha.1/dist/orderbook/OrderBook.js:152:26)
    at Array.forEach (<anonymous>)
    at OrderBook.addOwnOrder (/home/stephen/Desktop/xud-1.0.0-prealpha.1/dist/orderbook/OrderBook.js:150:25)
    at OrderBook.addLimitOrder (/home/stephen/Desktop/xud-1.0.0-prealpha.1/dist/orderbook/OrderBook.js:95:25)
    at Service.<anonymous> (/home/stephen/Desktop/xud-1.0.0-prealpha.1/dist/service/Service.js:132:53)
    at Generator.next (<anonymous>)
    at /home/stephen/Desktop/xud-1.0.0-prealpha.1/dist/service/Service.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/stephen/Desktop/xud-1.0.0-prealpha.1/dist/service/Service.js:3:12)
    at Service.placeOrder (/home/stephen/Desktop/xud-1.0.0-prealpha.1/dist/service/Service.js:129:38)
    at GrpcService.<anonymous> (/home/stephen/Desktop/xud-1.0.0-prealpha.1/dist/grpc/GrpcService.js:38:43)
    at Generator.next (<anonymous>)
    at /home/stephen/Desktop/xud-1.0.0-prealpha.1/dist/grpc/GrpcService.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/stephen/Desktop/xud-1.0.0-prealpha.1/dist/grpc/GrpcService.js:3:12)
    at GrpcService.unaryCall (/home/stephen/Desktop/xud-1.0.0-prealpha.1/dist/grpc/GrpcService.js:36:61)
    at GrpcService.<anonymous> (/home/stephen/Desktop/xud-1.0.0-prealpha.1/dist/grpc/GrpcService.js:84:18)
    at Generator.next (<anonymous>)
    at /home/stephen/Desktop/xud-1.0.0-prealpha.1/dist/grp

**Comment by kilrau** [comment]
Is this fixed for you on latest `master`? @liujiafeng622
