### ISSUE TITLE
xud-restart causes peers to fail

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#766]
I have a remote node running connected to xud1,2,3.
restarting xud3 with `xud-restart` yields this to my node:

```
TypeError: this.pairIds.values(...) is not a function or its return value is not iterable
    at Pool.OrderBook.removePeerOrders (/Users/admin/xud-simnet/xud/dist/orderbook/OrderBook.js:446:47)
    at Pool.emit (events.js:182:13)
    at Pool.<anonymous> (/Users/admin/xud-simnet/xud/dist/p2p/Pool.js:567:18)
    at Generator.next (<anonymous>)
    at /Users/admin/xud-simnet/xud/dist/p2p/Pool.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/admin/xud-simnet/xud/dist/p2p/Pool.js:3:12)
    at Pool.handlePeerClose (/Users/admin/xud-simnet/xud/dist/p2p/Pool.js:556:42)
    at Peer.peer.once (/Users/admin/xud-simnet/xud/dist/p2p/Pool.js:548:43)
    at Object.onceWrapper (events.js:273:13)
    at Peer.emit (events.js:182:13)
    at Peer.close (/Users/admin/xud-simnet/xud/dist/p2p/Peer.js:132:18)
    at Socket.socket.once (/Users/admin/xud-simnet/xud/dist/p2p/Peer.js:318:22)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:599:12)
/Users/admin/xud-simnet/xud/dist/bootstrap.js:13
        throw err;
        ^

TypeError: this.pairIds.values(...) is not a function or its return value is not iterable
    at Pool.OrderBook.removePeerOrders (/Users/admin/xud-simnet/xud/dist/orderbook/OrderBook.js:446:47)
    at Pool.emit (events.js:182:13)
    at Pool.<anonymous> (/Users/admin/xud-simnet/xud/dist/p2p/Pool.js:567:18)
    at Generator.next (<anonymous>)
    at /Users/admin/xud-simnet/xud/dist/p2p/Pool.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/admin/xud-simnet/xud/dist/p2p/Pool.js:3:12)
    at Pool.handlePeerClose (/Users/admin/xud-simnet/xud/dist/p2p/Pool.js:556:42)
    at Peer.peer.once (/Users/admin/xud-simnet/xud/dist/p2p/Pool.js:548:43)
    at Object.onceWrapper (events.js:273:13)
    at Peer.emit (events.js:182:13)
    at Peer.close (/Users/admin/xud-simnet/xud/dist/p2p/Peer.js:132:18)
    at Socket.socket.once (/Users/admin/xud-simnet/xud/dist/p2p/Peer.js:318:22)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:599:12)
admins-MacBook-Pro-2:xud-wd admin$ 
```

**Comment by sangaman** [comment]
@offerm Can you see if #768 fixes the issue for you? I wasn't able to reproduce using the latest from xud-simnet, starting and stopping works fine. I can't see why this error would come up, arrays have the `values()` function and `pairIds` should always be an array, but when looking at this I realized that I was converting an iterable to an array back to an iterable. It's unnecessary, but it shouldn't cause this bug. Still since I have no better explanation right now I'd be interested to see if that helps.
