### ISSUE TITLE
Can add order for WETH/BTC while raiden is disabled

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#983]
Disabling raiden in xud.conf still allows WETH/BTC order.

**Comment by kilrau** [comment]
A pity that this is not merged yet. Today I managed to crash xud without log entry when trying to swap weth/btc while raiden was down:

```
06/08/2019 12:14:08.695 [RAIDEN] error: failed to fetch channelbalances: Error: connect ECONNREFUSED 127.0.0.1:5001
06/08/2019 12:14:08.696 [RAIDEN] error: Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
06/08/2019 12:14:18.076 [RPC] debug: received call /xudrpc.Xud/PlaceOrderSync
06/08/2019 12:14:18.078 [ORDERBOOK] debug: reduced order 5a965df0-b827-11e9-a918-79ca38ae87e0 by 50000000 quantity while matching order f344f8d0-b832-11e9-9578-71d136397e62
06/08/2019 12:14:18.078 [ORDERBOOK] debug: matched with peer 03fd337659e99e628d0487e4f87acf93e353db06f754dccc402f2de1b857a319d0, executing swap on taker f344f8d0-b832-11e9-9578-71d136397e62 and maker 5a965df0-b827-11e9-a918-79ca38ae87e0 for 50000000
06/08/2019 12:14:18.127 [LND-BTC] debug: got 1 route(s) to destination 023f4a4fa9166f1beb2616bf0cce2c5a4fc9fcda6d533cb760bb6630487bfafdf9: 49900,2,1150002,54641329854021633,2500000000,1150000,2,49860,1150000000,2150,036f9b004f047283b33a640bc4afdd26e2eb82e73938f8ac0796641ad20dc5bdd4,17116097509785600,2500000$
06/08/2019 12:14:18.130 [SWAPS] debug: New deal: {"takerCltvDelta":5760,"rHash":"8232c4007213336822386a5916eb5582f4b7c9438ec9718269ef948c7f54aae6","orderId":"5a965df0-b827-11e9-a918-79ca38ae87e0","pairId":"WETH/BTC","proposedQuantity":50000000,"rPreimage":"d8179d1fa9a512fdbe758fd2a0ce33cceb5188efe683f9e62b9$
06/08/2019 12:14:18.133 [SWAPS] debug: Requesting deal: {"takerCltvDelta":5760,"rHash":"8232c4007213336822386a5916eb5582f4b7c9438ec9718269ef948c7f54aae6","orderId":"5a965df0-b827-11e9-a918-79ca38ae87e0","pairId":"WETH/BTC","proposedQuantity":50000000,"rPreimage":"d8179d1fa9a512fdbe758fd2a0ce33cceb5188efe683$
06/08/2019 12:14:18.338 [P2P] debug: received swapAccepted from 03fd337659e99e628d0487e4f87acf93e353db06f754dccc402f2de1b857a319d0: {"rHash":"8232c4007213336822386a5916eb5582f4b7c9438ec9718269ef948c7f54aae6","quantity":50000000,"makerCltvDelta":205}
06/08/2019 12:14:18.388 [LND-BTC] debug: executing sendPaymentSync -
          destination: 023f4a4fa9166f1beb2616bf0cce2c5a4fc9fcda6d533cb760bb6630487bfafdf9, rHash: 8232c4007213336822386a5916eb5582f4b7c9438ec9718269ef948c7f54aae6, amount: 1150000, FinalCltvDelta: 205
06/08/2019 12:14:48.345 [SWAPS] debug: deal 8232c4007213336822386a5916eb5582f4b7c9438ec9718269ef948c7f54aae6 failed due to SwapTimedOut: undefined
06/08/2019 12:14:48.353 [ORDERBOOK] error: swap between orders 5a965df0-b827-11e9-a918-79ca38ae87e0 & f344f8d0-b832-11e9-9578-71d136397e62 failed due to SwapTimedOut
06/08/2019 12:14:48.353 [ORDERBOOK] warn: swap for 50000000 failed during order matching due to SwapTimedOut, will repeat matching routine for failed quantity
06/08/2019 12:14:48.354 [ORDERBOOK] debug: repeating matching routine for f344f8d0-b832-11e9-9578-71d136397e62 for failed quantity of 50000000
06/08/2019 12:14:48.355 [ORDERBOOK] debug: placeOrder max time exceeded. order ({"pairId":"WETH/BTC","price":0.023,"quantity":50000000,"isBuy":true,"localId":"f344f8d0-b832-11e9-9578-71d136397e62","hold":0,"id":"f344f8d0-b832-11e9-9578-71d136397e62","initialQuantity":50000000,"createdAt":1565086458077}) won$
06/08/2019 12:14:48.356 [ORDERBOOK] debug: order added: {"pairId":"WETH/BTC","price":0.023,"quantity":50000000,"isBuy":true,"localId":"f344f8d0-b832-11e9-9578-71d136397e62","hold":0,"id":"f344f8d0-b832-11e9-9578-71d136397e62","initialQuantity":50000000,"createdAt":1565086458077}
06/08/2019 12:14:48.578 [LND-BTC] error: sendPaymentSync failed with payment error: UnknownPaymentHash(amt=1150000000 mSAT)
06/08/2019 12:14:48.580 [SWAPS] debug: new deal error message for 8232c4007213336822386a5916eb5582f4b7c9438ec9718269ef948c7f54aae6: + UnknownPaymentHash(amt=1150000000 mSAT)
06/08/2019 12:14:48.580 [LND-BTC] error: got exception from sendPaymentSync: {"dest":"","destString":"023f4a4fa9166f1beb2616bf0cce2c5a4fc9fcda6d533cb760bb6630487bfafdf9","amt":1150000,"paymentHash":"","paymentHashString":"8232c4007213336822386a5916eb5582f4b7c9438ec9718269ef948c7f54aae6","paymentRequest":"",$
    at LndClient.<anonymous> (/home/kilrau/xud-simnet/xud/dist/lndclient/LndClient.js:326:31)
    at Generator.next (<anonymous>)
    at fulfilled (/home/kilrau/xud-simnet/xud/dist/lndclient/LndClient.js:4:58)
06/08/2019 12:14:48.581 [SWAPS] debug: Sending swap error to peer: {"rHash":"8232c4007213336822386a5916eb5582f4b7c9438ec9718269ef948c7f54aae6","failureReason":7,"errorMessage":"UnknownPaymentHash(amt=1150000000 mSAT)"}
```
