### ISSUE TITLE
Raiden secret back to LND

### ISSUE THREAD

**Issue by offerm** [ExchangeUnion/xud#998]
@sangaman @karl need your help: Situation is like this - taker is doing
```
xucli buy 0.0001 WETH/BTC 0.0315
```
sending BTC, getting WETH.

maker received the BTC via hold invoice and now doing second leg (raiden payment).
Assume that this payment is good. XUD needs the result tokenPaymentResponse.secret to be able to provide it back to LND to settle the invoice.
My question - Does the code ready for the raiden response in this format:
```
{
  "secret_hash": "0x2eb110722be384d1af597f5e58de7a7b0e7bbf4c475c0f6511246d162d2aa86a",
  "identifier": 12760061994021652000,
  "initiator_address": "0x4F6799E2341379eA52213919622B9bEc80a1b655",
  "secret": "0x2ff886d47b156de00d4cad5d8c332706692b5b572adfe35e6d2f65e92906806e",
  "amount": 10,
  "token_address": "0x387d35a432Ee58a03034db5976c8412f573C387b",
  "hashalgo": "SHA256",
  "target_address": "0x133499f529A8D7cF00D8C5f7E73841DDB62b9Ca3"
}
```
**A hex string with 0x prefix?**

On the maker log I see this:
```
28/05/2019 21:46:39.925 [P2P] debug: received swapRequest from 028599d05b18c0c3f8028915a17d603416f7276c822b6b2d20e71a3502bd0f9e0a: {"proposedQuantity":10000,"pairId":"WETH/BTC","or
derId":"0e8d9980-8192-11e9-8b52-5f7ac5ad7904","rHash":"b8a0243672b503714822b454405de879e2b8300c7579d60295c35607ffd5613e","takerCltvDelta":1}
28/05/2019 21:46:39.927 [ORDERBOOK] debug: added hold of 10000 on order 0e8d9980-8192-11e9-8b52-5f7ac5ad7904
28/05/2019 21:46:39.930 [SWAPS] debug: New deal: {"proposedQuantity":10000,"pairId":"WETH/BTC","orderId":"0e8d9980-8192-11e9-8b52-5f7ac5ad7904","rHash":"b8a0243672b503714822b454405
de879e2b8300c7579d60295c35607ffd5613e","takerCltvDelta":1,"takerPubKey":"0x2B88992DEd5C96aa7Eaa9CFE1AE52350df7dc5DF","price":0.0315,"isBuy":false,"quantity":10000,"makerAmount":315
,"takerAmount":100000000000000,"makerCurrency":"BTC","takerCurrency":"WETH","destination":"0x2B88992DEd5C96aa7Eaa9CFE1AE52350df7dc5DF","peerPubKey":"028599d05b18c0c3f8028915a17d603
416f7276c822b6b2d20e71a3502bd0f9e0a","localId":"0e8d9980-8192-11e9-8b52-5f7ac5ad7904","phase":0,"state":0,"role":1,"createTime":1559079999929}
28/05/2019 21:46:39.932 [SWAPS] debug: got block height of 1
28/05/2019 21:46:39.933 [SWAPS] debug: total timelock of route = 0 makerCltvDelta = 144
28/05/2019 21:46:39.967 [LND] debug: BTC: added invoice of 315 for b8a0243672b503714822b454405de879e2b8300c7579d60295c35607ffd5613e
28/05/2019 21:46:39.972 [SWAPS] debug: Sending swap response to peer 
28/05/2019 21:46:40.308 [SWAPS] debug: Executing maker code to resolve hash
28/05/2019 21:46:43.660 [SWAPS] debug: Amount received for deal with payment hash 0x9f345e3751d8b7f38d34b7a3dd636a9d7a0c2f36d991615e6653501f30c6ec56
28/05/2019 21:46:43.662 [ORDERBOOK] debug: removed hold of 10000 on order 0e8d9980-8192-11e9-8b52-5f7ac5ad7904
28/05/2019 21:46:43.663 [ORDERBOOK] debug: order quantity reduced by 10000: 0e8d9980-8192-11e9-8b52-5f7ac5ad7904
28/05/2019 21:46:43.677 [SWAPS] error: could not settle invoice: Error: 2 UNKNOWN: invalid preimage length of 0, want 32
    at Object.exports.createStatusError (/opt/xud/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/opt/xud/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/opt/xud/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/opt/xud/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/opt/xud/node_modules/grpc/src/client_interceptors.js:845:24)
Let me know if you spot an issue.
```

**Comment by offerm** [comment]
response from raiden in this case was 
```
"response": {
    "amount": 100000000000000,
    "initiator_address": "0x7ed0299Fa1ADA71D10536B866231D447cDFa48b9",
    "secret_hash": "0xb8a0243672b503714822b454405de879e2b8300c7579d60295c35607ffd5613e",
    "secret": "0x9f345e3751d8b7f38d34b7a3dd636a9d7a0c2f36d991615e6653501f30c6ec56",
    "identifier": 3820989367401102,
    "hashalgo": "SHA256",
    "target_address": "0x2B88992DEd5C96aa7Eaa9CFE1AE52350df7dc5DF",
    "token_address": "0x4c354C76d5f73A63a90Be776897DC81Fb6238772"
  },
```

**Comment by kilrau** [comment]
This should be fixed as per call, if not reopen @offerm
